### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by WhozKunal** [marcelotduarte/cx_Freeze#2559] opened 2024-09-04 19:16 UTC
from cx_Freeze import setup, Executable
import sys

sys.setrecursionlimit(5000)

ffmpeg_path = "C:\\ffmpeg\\bin\\ffmpeg.exe"

# Define build options including additional packages and files
build_options = {
    'packages': ['av', 'threading', 'concurrent.futures', 'os', 'time',
                 'numpy','torch', 'transformers', 'pyannote', 'flask','torch','docx'],  
    
    
    
    'excludes': [],
    'include_files': [
        ('C:\\upsala\\Pratilekh\\env\\Lib\\site-packages\\transformers', 'lib\\transformers'),
        
        (ffmpeg_path, 'ffmpeg.exe'),
    ],
    'include_msvcr': True, 
}

# Determine base depending on platform
base = 'Win64GUI' if sys.platform == 'win64' else None

# Define the executable
executables = [
    Executable('Kunal.py', base=base)
]

# Setup configuration
setup(
    name='Kunal',
    version='1.0',
    description='Kunal',
    options={'build_exe': build_options},
    executables=executables
)

error = 

Traceback (most recent call last):
  File "C:\upsala\Pratilekh\env\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 141, in run
    module_init.run(name + "__main__")
  File "C:\upsala\Pratilekh\env\Lib\site-packages\cx_Freeze\initscripts\console.py", line 25, in run
    exec(code, main_globals)
  File "Kunal.py", line 14, in <module>
  File "C:\upsala\Pratilekh\constants.py", line 2, in <module>
    import whisperx
  File "C:\upsala\Pratilekh\env\lib\site-packages\whisperx\__init__.py", line 1, in <module>
    from .transcribe import load_model
  File "C:\upsala\Pratilekh\env\lib\site-packages\whisperx\transcribe.py", line 10, in <module>
    from .asr import load_model
  File "C:\upsala\Pratilekh\env\lib\site-packages\whisperx\asr.py", line 13, in <module>
    from .vad import load_vad_model, merge_chunks
  File "C:\upsala\Pratilekh\env\lib\site-packages\whisperx\vad.py", line 11, in <module>
    from pyannote.audio.pipelines import VoiceActivityDetection
  File "C:\upsala\Pratilekh\env\lib\site-packages\pyannote\audio\pipelines\__init__.py", line 26, in <module>
    from .speaker_diarization import SpeakerDiarization
  File "C:\upsala\Pratilekh\env\lib\site-packages\pyannote\audio\pipelines\speaker_diarization.py", line 42, in <module>
    from pyannote.audio.pipelines.speaker_verification import PretrainedSpeakerEmbedding
  File "C:\upsala\Pratilekh\env\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py", line 45, in <module>
    from speechbrain.pretrained import (
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 108, in __getattr__
    return getattr(self.ensure_module(1), attr)
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 168, in ensure_module
    module = super().ensure_module(stacklevel + 1)
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 76, in ensure_module
    importer_frame = inspect.getframeinfo(sys._getframe(stacklevel + 1))
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1627, in getframeinfo
    lines, lnum = findsource(frame)
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 952, in findsource
    module = getmodule(object, file)
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 869, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 108, in __getattr__
    return getattr(self.ensure_module(1), attr)
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 168, in ensure_module
    module = super().ensure_module(stacklevel + 1)
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 76, in ensure_module
    importer_frame = inspect.getframeinfo(sys._getframe(stacklevel + 1))
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1627, in getframeinfo
    lines, lnum = findsource(frame)
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 952, in findsource
    module = getmodule(object, file)
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 869, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 108, in __getattr__
    return getattr(self.ensure_module(1), attr)
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 168, in ensure_module
    module = super().ensure_module(stacklevel + 1)
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 76, in ensure_module
    importer_frame = inspect.getframeinfo(sys._getframe(stacklevel + 1))
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1627, in getframeinfo
    lines, lnum = findsource(frame)
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 952, in findsource
    module = getmodule(object, file)
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 869, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 108, in __getattr__
    return getattr(self.ensure_module(1), attr)
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 168, in ensure_module
    module = super().ensure_module(stacklevel + 1)
  File "C:\upsala\Pratilekh\env\lib\site-packages\speechbrain\utils\importutils.py", line 76, in ensure_module
    importer_frame = inspect.getframeinfo(sys._getframe(stacklevel + 1))
  File "C:\Users\sss\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1627, in getframeinfo
    lines, lnum =

**Comment by marcelotduarte** [comment] 2024-09-07 22:19
Duplicate of #2273

**Closed as completed by marcelotduarte** 2024-09-07 22:19 UTC
