### ISSUE TITLE
cx-freeze doesn't find all dependencies tkinter

### ISSUE THREAD

**Issue by ghost** [marcelotduarte/cx_Freeze#671] opened 2020-06-11 19:30 UTC
Skip to content
Pull requests
Issues
Marketplace
Explore
@marcelotduarte
anthony-tuininga /
cx_Freeze

30
543

    124

Code
Issues 102
Pull requests 12
Actions
Projects
Wiki
Security

    Insights

f #671
Closed
Lucysmith8 opened this issue 16 days ago · 1 comment
Comments
@Lucysmith8
Lucysmith8 commented 16 days ago •
Edited 1 time

    @Lucysmith8 Lucysmith8 edited 16 days ago (most recent)

No description provided.
@marcelotduarte
Collaborator
marcelotduarte commented 16 days ago

I think your issue is with tensorflow, not tkinter.
Duplicate of #646 or #380
@marcelotduarte marcelotduarte closed this 16 days ago
@Lucysmith8 Lucysmith8 changed the title cx-freeze doesn't find all dependencies tkinter f 16 days ago
@marcelotduarte
Attach files by dragging & dropping, selecting or pasting them.
Remember, contributions to this repository should follow our GitHub Community Guidelines.
Assignees
No one—
Labels
None yet
Projects
None yet
Milestone
No milestone
Linked pull requests

Successfully merging a pull request may close this issue.
None yet
Notifications
Customize

You’re receiving notifications because you’re watching this repository.
2 participants
@marcelotduarte
@Lucysmith8
Lock conversation
Transfer issue

    © 2020 GitHub, Inc.
    Terms
    Privacy
    Security
    Status
    Help

    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

@Lucysmith8 Lucysmith8 edited 16 days ago

I use cx freeze to distribute my application with TKinter. Everything works perfectly, but I have a problem with only one module, it's tensorflow. When I run my script from conda, tensorflow works perfectly. But when I freeze with pip setup.py build, I have a problem.

error

Can I enter the path for the module or import it directly? Or is the solution not to package?

import cx_Freeze as cx

include_files = [('package/images', 'images'), ('package/model', 'model')]

cx.setup(

    name='myScript',

    version='1.0',

    author='author',

    description='MyScript description',

    packages=['package'],

    executables=[

        cx.Executable('myScript.py',

                      targetName='folder', icon='myScript.ico')],

    options={

        'build_exe': {

            'packages': ['tensorflow', 'tkinter'],

            'includes': ['idna.idnadata', 'zlib'],

            'excludes': ['PyQt4', 'PyQt5', 'PySide', 'IPython',

                         'jupyter_client', 'jupyter_core', 'ipykernel',

                         'ipython_genutils', 'Tkinter'],

            'include_files': include_files

        }

    }

)

**Comment by marcelotduarte** [comment] 2020-06-11 22:35
I think your issue is with tensorflow, not tkinter.
Duplicate of #646 or #380

**Closed as completed by marcelotduarte** 2020-06-11 22:35 UTC
