### ISSUE TITLE
Problem with application launch

### ISSUE THREAD

**Issue by cainesi** [marcelotduarte/cx_Freeze#713] opened 2020-07-26 03:56 UTC
I'm running into a problem where launching a frozen application from the command line on OSX results in the following error:

```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```

The error does **not** occur when the application is run on the original computer, but does occur when run on a clean machine.  I debugged, and the error is occurring at the following line of Console.c, in the InitializePython() function (the non-windows version):

```
    Py_Initialize();
```

Swapping in a Console file from an older version of cx-Freeze resolves the issue.

The issue may be related to the change in revision 8762f3e803 that reordered the code so that Py_Initialize is run before the module search path is set?

**Comment by marcelotduarte** [comment] 2020-07-26 06:24
Duplicate of #667
Please, subscribe to that issue.

**Closed as completed by marcelotduarte** 2020-07-26 06:24 UTC
