### ISSUE TITLE
put dll files in lib folder

### ISSUE THREAD

**Issue by stephenmhall** [marcelotduarte/cx_Freeze#515] opened 2019-09-19 20:46 UTC
would it be possible to change the exe so it looks for the pythonX.dll and api-*.dll files in the lib folder and just leave the app.exe file in the top level folder. Just to make it look neater and less cluttered for users.

**Comment by marcelotduarte** [comment] 2020-02-23 08:14
Duplicate of #237

**Closed as completed by marcelotduarte** 2020-02-23 08:14 UTC
