### ISSUE TITLE
tkinter import error

### ISSUE THREAD

**Issue by iRusher28** [marcelotduarte/cx_Freeze#656] opened 2020-05-20 16:31 UTC
Hello, I had an error with cx_freeze copying Tkinter il libs instead of tkinter, causing Python not to find it while running the .exe file.

I just had to rename the folder in libs from Tkinter to tkinter for the script to work well !

Thanks !

**Comment by marcelotduarte** [comment] 2020-05-20 17:00
Duplicate of #567 
PR #576 solves this issue.

**Closed as completed by marcelotduarte** 2020-05-20 17:00 UTC
