### ISSUE TITLE
Can't install cx_Freeze for Python 3.7 on Windows 10.

### ISSUE THREAD

**Issue by LightUmbra** [marcelotduarte/cx_Freeze#410] opened 2018-08-05 22:53 UTC
I'm trying to install cx_Freeze for my python 3.7 install. I used pip install cx_freeze.

This was my error message. [Here is a install I ran with the -v flag.](https://pastebin.com/un1UMgD3) 

Collecting cx_freeze
  Using cached https://files.pythonhosted.org/packages/5f/16/eab51d6571dfec2554248cb027c51babd04d97f594ab6359e0707361297d/cx_Freeze-5.1.1.tar.gz
Installing collected packages: cx-freeze
  Running setup.py install for cx-freeze: started
    Running setup.py install for cx-freeze: finished with status 'error'
    Complete output from command c:\users\joe\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Joe\\AppData\\Local\\Temp\\pip-install-2zf__d8q\\cx-freeze\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Joe\AppData\Local\Temp\pip-record-585ck1f0\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\common.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\dist.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\finder.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\freezer.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\hooks.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\macdist.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\main.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\setupwriter.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\windist.py -> build\lib.win-amd64-3.7\cx_Freeze
    copying cx_Freeze\__init__.py -> build\lib.win-amd64-3.7\cx_Freeze
    creating build\lib.win-amd64-3.7\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\Console.py -> build\lib.win-amd64-3.7\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\ConsoleSetLibPath.py -> build\lib.win-amd64-3.7\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\SharedLib.py -> build\lib.win-amd64-3.7\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\SharedLibSource.py -> build\lib.win-amd64-3.7\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\__startup__.py -> build\lib.win-amd64-3.7\cx_Freeze\initscripts
    creating build\lib.win-amd64-3.7\cx_Freeze\samples
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\advanced
    copying cx_Freeze\samples\advanced\advanced_1.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\advanced
    copying cx_Freeze\samples\advanced\advanced_2.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\advanced
    copying cx_Freeze\samples\advanced\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\advanced
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\asmodule
    copying cx_Freeze\samples\asmodule\asmodule.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\asmodule
    copying cx_Freeze\samples\asmodule\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\asmodule
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\matplotlib
    copying cx_Freeze\samples\matplotlib\matplotlib_eg.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\matplotlib
    copying cx_Freeze\samples\matplotlib\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\matplotlib
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\openpyxl
    copying cx_Freeze\samples\openpyxl\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\openpyxl
    copying cx_Freeze\samples\openpyxl\test_openpyxl.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\openpyxl
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt4
    copying cx_Freeze\samples\PyQt4\PyQt4app.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt4
    copying cx_Freeze\samples\PyQt4\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt4
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt5
    copying cx_Freeze\samples\PyQt5\PyQt5app.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt5
    copying cx_Freeze\samples\PyQt5\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\PyQt5
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\relimport
    copying cx_Freeze\samples\relimport\relimport.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\relimport
    copying cx_Freeze\samples\relimport\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\relimport
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\service
    copying cx_Freeze\samples\service\Config.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\service
    copying cx_Freeze\samples\service\ServiceHandler.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\service
    copying cx_Freeze\samples\service\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\service
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\simple
    copying cx_Freeze\samples\simple\hello.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\simple
    copying cx_Freeze\samples\simple\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\simple
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\Tkinter
    copying cx_Freeze\samples\Tkinter\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\Tkinter
    copying cx_Freeze\samples\Tkinter\SimpleTkApp.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\Tkinter
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\wx
    copying cx_Freeze\samples\wx\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\wx
    copying cx_Freeze\samples\wx\wxapp.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\wx
    creating build\lib.win-amd64-3.7\cx_Freeze\samples\zope
    copying cx_Freeze\samples\zope\qotd.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\zope
    copying cx_Freeze\samples\zope\setup.py -> build\lib.win-amd64-3.7\cx_Freeze\samples\zope
    running build_ext
    building 'cx_Freeze.util' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\source
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\joe\appdata\local\programs\python\python37\include -Ic:\users\joe\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.17134.0\ucrt" "-ID:\Windows Kits\10\include\10.0.17134.0\shared" "-ID:\Windows Kits\10\include\10.0.17134.0\um" "-ID:\Windows Kits\10\include\10.0.17134.0\winrt" "-ID:\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcsource/util.c /Fobuild\temp.win-amd64-3.7\Release\source/util.obj
    util.c
    source/util.c(277): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'long'
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\joe\appdata\local\programs\python\python37\libs /LIBPATH:c:\users\joe\appdata\local\programs\python\python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17134.0\um\x64" imagehlp.lib Shlwapi.lib /EXPORT:PyInit_util build\temp.win-amd64-3.7\Release\source/util.obj /OUT:build\lib.win-amd64-3.7\cx_Freeze\util.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\source\util.cp37-win_amd64.lib
       Creating library build\temp.win-amd64-3.7\Release\source\util.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\source\util.cp37-win_amd64.exp
    Generating code
    Finished generating code
    creating build\temp.win-amd64-3.7\Release\source\bases
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\joe\appdata\local\programs\python\python37\include -Ic:\users\joe\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.17134.0\ucrt" "-ID:\Windows Kits\10\include\10.0.17134.0\shared" "-ID:\Windows Kits\10\include\10.0.17134.0\um" "-ID:\Windows Kits\10\include\10.0.17134.0\winrt" "-ID:\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcsource/bases/Console.c /Fobuild\temp.win-amd64-3.7\Release\source/bases/Console.obj
    Console.c
    creating C:\Users\Joe\AppData\Local\Temp\pip-install-2zf__d8q\cx-freeze\build\lib.win-amd64-3.7\cx_Freeze\bases
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:c:\users\joe\appdata\local\programs\python\python37\libs /LIBPATH:c:\users\joe\appdata\local\programs\python\python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17134.0\um\x64" imagehlp.lib Shlwapi.lib build\temp.win-amd64-3.7\Release\source/bases/Console.obj /OUT:build\lib.win-amd64-3.7\cx_Freeze\bases\Console.exe /MANIFEST
    Generating code
    Finished generating code
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\joe\appdata\local\programs\python\python37\include -Ic:\users\joe\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.17134.0\ucrt" "-ID:\Windows Kits\10\include\10.0.17134.0\shared" "-ID:\Windows Kits\10\include\10.0.17134.0\um" "-ID:\Windows Kits\10\include\10.0.17134.0\winrt" "-ID:\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tcsource/bases/Win32GUI.c /Fobuild\temp.win-amd64-3.7\Release\source/bases/Win32GUI.obj
    Win32GUI.c
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:c:\users\joe\appdata\local\programs\python\python37\libs /LIBPATH:c:\users\joe\appdata\local\programs\python\python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17134.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.17134.0\um\x64" imagehlp.lib Shlwapi.lib user32.lib build\temp.win-amd64-3.7\Release\source/bases/Win32GUI.obj /OUT:build\lib.win-amd64-3.7\cx_Freeze\bases\Win32GUI.exe /MANIFEST
    Generating code
    Finished generating code
    running build_scripts
    creating build\scripts-3.7
    copying and adjusting cxfreeze -> build\scripts-3.7
    copying and adjusting cxfreeze-quickstart -> build\scripts-3.7
    error: file 'C:\Users\Joe\AppData\Local\Temp\pip-install-2zf__d8q\cx-freeze\cxfreeze-postinstall' does not exist
    
    Running setup.py install for cx-freeze: finished with status 'error'
Cleaning up...
  Removing source in C:\Users\Joe\AppData\Local\Temp\pip-install-enjvt4h5\cx-freeze
Removed build tracker 'C:\\Users\\Joe\\AppData\\Local\\Temp\\pip-req-tracker-0gyjc4fa'
Exception information:
Traceback (most recent call last):
  File "c:\users\joe\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File "c:\users\joe\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\commands\install.py", line 347, in run
    use_user_site=options.use_user_site,
  File "c:\users\joe\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\req\__init__.py", line 49, in install_given_reqs
    **kwargs
  File "c:\users\joe\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\req\req_install.py", line 972, in install
    spinner=spinner,
  File "c:\users\joe\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\utils\misc.py", line 701, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "c:\users\joe\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Joe\\AppData\\Local\\Temp\\pip-install-enjvt4h5\\cx-freeze\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Joe\AppData\Local\Temp\pip-record-1m7e8kbv\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Joe\AppData\Local\Temp\pip-install-enjvt4h5\cx-freeze\
    ----------------------------------------

**Comment by LeonarddeR** [comment] 2018-08-06 17:59
Looks like a duplicate of #407

**Comment by rodolvbg** [comment] 2019-07-28 01:02
The same happens to me

**Comment by SuzukiHonoka** [comment] 2019-08-13 15:06
Same here.

**Comment by marcelotduarte** [comment] 2019-08-13 16:48
Version 5.x doesn't support py37. A beta version 6.0 has partial support. See comment of the author at issue #496.

**Comment by anthony-tuininga** [comment] 2019-08-30 03:08
cx_Freeze 6 has been released with support for Python 3.7.

**Closed as completed by anthony-tuininga** 2019-08-30 03:08 UTC

**Comment by careyshan** [comment] 2019-08-30 08:07
It won't install on Ubuntu however - do you think you will get a chance to update it for ubuntu Anthony? Thanks

**Comment by marcelotduarte** [comment] 2019-08-30 15:55
For me it install. Please open a issue and show the error messages.

**Comment by DanPetersson** [comment] 2019-12-30 07:27
I have the same issue now when trying to install cx_Freeze 6 on Python 3.8.
pip install cx-Freeze
python -m pip install cx_Freeze --upgrade

Should I create a new issue ticket for this?
---------------------------------------------
...
    running build_scripts
    creating build\scripts-3.8
    copying and adjusting cxfreeze -> build\scripts-3.8
    copying and adjusting cxfreeze-quickstart -> build\scripts-3.8
    error: file 'C:\Users\danpe\AppData\Local\Temp\pip-install-j8y6pe_6\cx-Freeze\cxfreeze-postinstall' does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\danpe\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\danpe\\AppData\\Local\\Temp\\pip-install-j8y6pe_6\\cx-Freeze\\setup.py'"'"'; __file__='"'"'C:\\Users\\danpe\\AppData\\Local\\Temp\\pip-install-j8y6pe_6\\cx-Freeze\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\danpe\AppData\Local\Temp\pip-record-vyfec_qq\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by marcelotduarte** [comment] 2019-12-30 12:46
Your error in py38 is the same issue as #56 
PR #511 solve this issue.
It'll be available in the next release, coming soon.
