### ISSUE TITLE
cxfreeze-postinstall does not exist

### ISSUE THREAD

**Issue by stolk** [marcelotduarte/cx_Freeze#544] opened 2019-12-20 21:57 UTC
**C:\Python38>python -m pip install cx_Freeze --upgrade**

```
...
error: file 'C:\Users\abrahamstolk\AppData\Local\Temp\pip-install-0b_ppmz6\cx-Freeze\cxfreeze-postinstall' does not exist
 ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\abrahamstolk\\AppData\\Local\\Temp\\pip-install-0b_ppmz6\\cx-Freeze\\setup.py'"'"'; __file__='"'"'C:\\Users\\abrahamstolk\\AppData\\Local\\Temp\\pip-install-0b_ppmz6\\cx-Freeze\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\abrahamstolk\AppData\Local\Temp\pip-record-800iwjdj\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

This is on Windows 10, with Python 3.8 and latest PIP module.

**Comment by stolk** [comment] 2019-12-20 22:17
Installing from github does work, btw:

https://github.com/anthony-tuininga/cx_Freeze/issues/407#issuecomment-453035642

**Comment by marcelotduarte** [comment] 2019-12-20 22:31
Do you have a C compiler? if not, install the latest version using:
pip install -U cx-freeze

**Comment by marcelotduarte** [comment] 2019-12-27 20:35
PR #511 solves this issue.
Duplicate of #56

**Closed as completed by marcelotduarte** 2019-12-27 20:35 UTC
Labels: duplicate

**Comment by marcelotduarte** [comment] 2020-01-05 04:47
cx_Freeze 6.1 has just been released.
