### ISSUE TITLE
cx_Freeze module not found when using python -m build

### ISSUE THREAD

**Issue by jschwar313** [marcelotduarte/cx_Freeze#1731] opened 2022-12-28 14:31 UTC
**Prerequisite**
 - Make sure no duplicated issue has already been reported. You should look for closed issues, too.
 - Make sure you are not asking us to help to solve your specific issue. GitHub issues are opened mainly for development purposes. If you want to ask someone to help to solve your problem, go to some community site like StackOverflow, etc.
 - Make sure your problem is not derived from packaging (e.g. Homebrew).

**Describe the bug**
Does cx_Freeze support using the python -m build way of building a project?  I'm converting from using python setup.py bdist_msi, which is deprecated now, to using python -m build, but I get an error.  I've attached my setup.py and pyproject.toml files.  Here's the link saying it's deprecated:  https://setuptools.pypa.io/en/latest/userguide/quickstart.html

**To Reproduce**
python -m build

**Expected behavior**
An error shouldn't be produced.

**Screenshots**

**Desktop (please complete the following information):**
 - Platform information: Windows 10, 64-bit
 - OS architecture (e.g. amd64): 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz   2.59 GHz
 - cx_Freeze version [e.g. 6.11]: 6.13.1
 - Python version [e.g. 3.10]: 3.11.1

**Additional context**
Here's the error that's listed:

(prod) H:\Users\LindaJim\Documents\SourceCode\Software\aws_pc_backup\prod>python -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools)
* Getting build dependencies for sdist...
Traceback (most recent call last):
  File "H:\Users\LindaJim\Documents\SourceCode\Software\aws_pc_backup\prod\Lib\site-packages\pep517\in_process\_in_process.py", line 351, in <module>
    main()
  File "H:\Users\LindaJim\Documents\SourceCode\Software\aws_pc_backup\prod\Lib\site-packages\pep517\in_process\_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Users\LindaJim\Documents\SourceCode\Software\aws_pc_backup\prod\Lib\site-packages\pep517\in_process\_in_process.py", line 285, in get_requires_for_build_sdist
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jschw\AppData\Local\Temp\build-env-7icq_pfv\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jschw\AppData\Local\Temp\build-env-7icq_pfv\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "C:\Users\jschw\AppData\Local\Temp\build-env-7icq_pfv\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cx_Freeze'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist

[pyproject.toml.txt](https://github.com/marcelotduarte/cx_Freeze/files/10314694/pyproject.toml.txt)

[setup.py.txt](https://github.com/marcelotduarte/cx_Freeze/files/10314696/setup.py.txt)

**Comment by marcelotduarte** [comment] 2022-12-28 17:30
Duplicate of #1491 

> Does cx_Freeze support using the python -m build way of building a project?

No.
[Build](https://pypi.org/project/build/) is "A simple, correct PEP 517 build frontend."
The objective of cx_Freeze is to "Create standalone executables..." and PEP517 define how to create sdist and wheels, and PEP518 defines file-formats overwriting PEP508.
So, this is not a bug. Obviously, we can use the same ideas to create executables instead of wheels.

There is nothing in the [documentation](https://cx-freeze.readthedocs.io/) that suggests this is the command to build cx_Freeze. The correct in any environment is:
`python setup.py build`

> Here's the link saying it's deprecated: https://setuptools.pypa.io/en/latest/userguide/quickstart.html

`python setup.py bdist_msi` continues valid in cx_Freeze. It is removed from python 3.11 and setuptools, but I ported it to cx_Freeze and it can work until 3.12 (See discution #1721).

If you check the error of the first command you tried:
> ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist

This error is correct because cx_Freeze does not build sdist. It build exe, msi, rpm....

I understand that you are suggesting the support for a PEP517-like feature, supporting pyproject.toml.
Alias, pyproject.toml already can be used in conjunction to setup.py (only basic metadata and commands).
Subscribe to #1569 for news.

**Closed as completed by marcelotduarte** 2022-12-28 17:30 UTC
