### ISSUE TITLE
Replacement for deprecated bdist_msi

### ISSUE THREAD

**Issue by vashek** [marcelotduarte/cx_Freeze#1622] opened 2022-09-29 19:39 UTC
setup.py bdist_msi is deprecated starting from Python 3.9 and is going to be gone in 3.11 (see https://bugs.python.org/issue39586). Is there any battle plan for replacing it, or ideas for another simple, ideally backwards-compatible, solution?

(If not, consider this a documentation bug for https://cx-freeze.readthedocs.io/en/latest/setup_script.html)

**Comment by marcelotduarte** [comment] 2022-09-29 20:49
Duplicate of #1254

You are a little late. Since version 6.11 (we are on 6.11.1) bdist_msi has been merged into cx_Freeze (PR #1447 and others).
By being deprecated and later dropped from python doesn't mean it needs to be replaced, we can keep using it as long as I maintain it.
In setuptools something similar happens, distutils has been deprecated, and is now being merged into setuptools.

**Closed as completed by marcelotduarte** 2022-09-29 20:49 UTC

**Comment by vashek** [comment] 2022-09-29 21:00
Oh wow, that's great, thank you!
And sorry about not finding the already existing issue. (May I suggest fixing the typo in its title? I mean I still should have found it of course...)

**Comment by marcelotduarte** [comment] 2022-09-29 22:55
No problem. I fixed the title.
