### ISSUE TITLE
Fatal Python error: initfsencoding: Unable to get the locale encoding

### ISSUE THREAD

**Issue by kk21986** [marcelotduarte/cx_Freeze#538] opened 2019-12-14 19:22 UTC
I have installed cx_Freeze 6.0 on python 3.7.1 and getting the below error,

```
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f7a7eee1740 (most recent call first):
Aborted

```
I see you have said that this issue fixed on 6.0 in the port[399]( https://github.com/anthony-tuininga/cx_Freeze/issues/399) but still appearing.

**Comment by marcelotduarte** [comment] 2019-12-14 20:51
Let us know more about your system.
What OS?
What distribution? From python.org, Anaconda?
And other information you find important.

**Comment by anthony-tuininga** [comment] 2019-12-14 20:53
And if you can provide a script and its corresponding setup.py that would be extremely helpful. Otherwise, we're stuck guessing what you did (or didn't do!)

**Comment by kk21986** [comment] 2019-12-15 02:14
Redhat7. I found the issue and sorry this is the first time am trying this cx_Freeze. Basically I have the below directory structure for my project.

```
├── project_name
│   ├── start.py
│   ├── __main__.py
│   ├── __init__.py
│   ├── common_libs
│   │   └── __init__.py
│   ├── project_code
│   │   ├── <core files to run the project>
│   │   ├── __init__.py
│   ├── etc
│   │   ├── auto_config.ini
│   ├── modules
│   │   ├── __init__.py
│   │   ├── <all the modules required to run the scripts in auto folder
│   ├── auto
│   │   ├── __init__.py
│   │   ├── <all the scripts under this folder and the respective modules are in the modules folder>
│   └── utils
│       ├── configuration.py
│       ├── __init__.py
│       ├── logger.py
│       ├── decrypt.py
│       └── utils.py

```

In this project internally I call each scripts based on the requirements and the script files are located under auto of the project directory. So by just freezing the __main__.py in project home will not work. What I have tried is to freeze all the scripts separately in the scripts folder under build/exe.linux-x86_64-3.7 and then freeze __main__.py of project_home. After freezing all I got the below tree structure,

```
# ls build/exe.linux-x86_64-3.7/
project_bin  lib  scripts

```
So when I tried to any of the script standalone(not through the project_bin just for testing where the frozen script is working) ended up with that error. After digging I tried to copy the lib folder from build/exe.linux-x86_64-3.7/ to build/exe.linux-x86_64-3.7/scripts as well and it worked. But now I have got a different error,

```
# ./build/exe.linux-x86_64-3.7/scripts/test_script -a arg1
Traceback (most recent call last):
  File "/usr/local/python371/lib/python3.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 39, in run
    module = __import__(name + "__init__")
ModuleNotFoundError: No module named 'test_script__init__'

```
Here is the setup.py

```
import sys
from cx_Freeze import setup, Executable

scripts_options = {
    'build_exe': {
        'includes': ['project_name'],
        'packages': ['project_name.scripts', 'project_name.modules', 'project_name.utils'],
        'path': sys.path + ['/home/user/', '/home/user/project_name'],
        'silent': True,
    }
}

scripts_executables = [
    Executable('/home/user/project_name/scripts/test_script.py',
               targetName='scripts/test_script'),
    Executable('/home/user/project_name/scripts/test_another.py',
               targetName='scripts/test_another'),
]

options = {
    'build_exe': {
        'includes': ['project_name', 'configparser', 'yaml', 'logging', 'logging.config'],
        'packages': ['project_name.scripts', 'project_name.modules', 'project_name.utils'],
        'path': sys.path + ['/home/user/', '/home/user/project_name'],
        'silent': True,
    }
}

executables = [
    Executable('/home/user/project_name/__main__.py', targetName='project_bin'),
]

setup(name='Test Project Scripts',
      version='1.0',
      description='This is just test project for cx_Freeze',
      options=scripts_options,
      executables=scripts_executables
      )

setup(name='Test Project',
      version='1.0',
      description='This is just test project for cx_Freeze',
      options=options,
      executables=executables
      )


```

**Comment by marcelotduarte** [comment] 2019-12-26 05:30
You didn't answer my questions well, but I can deduce that you use python compiled from python.org sources or anaconda, since it is installed in /usr/local.
PR #518 takes care of these initially pointed problem, so:

1) Use current version
pip install -U git+https://github.com/anthony-tuininga/cx_Freeze.git

2) The other problems I see is transferring generate executables in a scripts folder, and this causes ModuleNotFoundError. As you generate executables from these scripts, they have to be in the main folder and you then adapt your code to that (and you will, because you will no longer call the scripts but executables).
2.1) In scripts_executables you use targetName including a relative path. This will go wrong, it was designed for you to set the name only (targetName), otherwise it would be called targetPath (this doesn't exist).
2.2) A possible undocumented exception would be to be able to put this script in lib/test_script.

**Comment by marcelotduarte** [comment] 2020-01-05 05:20
cx_Freeze 6.1 has just been released.
Assuming this has been resolved.
If you had issues please re-open.

**Closed as completed by marcelotduarte** 2020-01-05 05:20 UTC
