### ISSUE TITLE
ImportError: libffi-ae16d830.so.6.0.4

### ISSUE THREAD

**Issue by 1marc1** [marcelotduarte/cx_Freeze#464] opened 2019-03-30 12:01 UTC
Hi,

I am getting an odd error when working with the cryptography packages. Here are some details of my Ubuntu 16.04 environment:

```
marc@ubuntu:/tmp/test$ cxfreeze --version
cxfreeze 5.1.1
Copyright (c) 2007-2017 Anthony Tuininga. All rights reserved.
Copyright (c) 2001-2006 Computronix Corporation. All rights reserved.
marc@ubuntu:/tmp/test$ python3 --version
Python 3.5.2
```
The output below shows the sample code that isolates the issue. When executing this file from Python, there is no problem and everything works as expected.
```
marc@ubuntu:/tmp/test$ cat helloworld.py 
from cryptography.fernet import Fernet

print ('Hello world')
marc@ubuntu:/tmp/test$ python3 helloworld.py 
Hello world
```
Next, I proceed to freeze the application with cxfreeze, as follows:
```
marc@ubuntu:/tmp/test$ cxfreeze helloworld.py --include-modules=_cffi_backend --silent
Missing modules:
? StringIO imported from six
? UserDict imported from asn1crypto._ordereddict
? __main__ imported from bdb, pdb
? _dummy_threading imported from dummy_threading
? _frozen_importlib imported from importlib, importlib.abc
? _frozen_importlib_external imported from importlib, importlib._bootstrap, importlib.abc
? _winapi imported from subprocess
? _winreg imported from platform
? cStringIO imported from asn1crypto.core
? ce imported from os
? ctypes.macholib.dyld imported from ctypes.util
? java.lang imported from platform
? msvcrt imported from subprocess
? nt imported from ntpath, os, shutil
? org.python.core imported from copy
? os.path imported from os, pkgutil, py_compile, unittest, unittest.util
? six.moves imported from cryptography.x509.general_name
? urllib.quote imported from asn1crypto._iri
? urllib.unquote imported from asn1crypto._iri
? urlparse imported from asn1crypto._iri
? vms_lib imported from platform
? winreg imported from mimetypes, platform
This is not necessarily a problem - the modules may not be needed on this platform.
```
When I then proceed to run my application, the following happens:
```
marc@ubuntu:/tmp/test$ dist/helloworld 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/usr/local/lib/python3.5/dist-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "helloworld.py", line 1, in <module>
    from cryptography.fernet import Fernet
  File "/home/marc/.local/lib/python3.5/site-packages/cryptography/fernet.py", line 17, in <module>
    from cryptography.hazmat.primitives import hashes, padding
  File "/home/marc/.local/lib/python3.5/site-packages/cryptography/hazmat/primitives/padding.py", line 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ImportError: libffi-ae16d830.so.6.0.4: cannot open shared object file: No such file or directory
```
Based on the output from the above, one would say that for some reason the file `libffi-ae16d830.so.6.0.4` was not included, however, when looking at the output of the next command, we see that the file is present in the lib directory.
```
marc@ubuntu:/tmp/test$ ll dist/lib
total 3364
drwxrwxr-x 17 marc marc   4096 Mar 30 22:45 ./
drwxrwxr-x  3 marc marc   4096 Mar 30 22:45 ../
drwxrwxr-x  3 marc marc   4096 Mar 30 22:42 asn1crypto/
-rw-r--r--  1 marc marc  22000 Nov 13 03:27 _bz2.cpython-35m-x86_64-linux-gnu.so
-rwxrwxr-x  1 marc marc 833112 Sep 23  2018 _cffi_backend.cpython-35m-x86_64-linux-gnu.so*
-rw-r--r--  1 marc marc 149880 Nov 13 03:27 _codecs_cn.cpython-35m-x86_64-linux-gnu.so
-rw-r--r--  1 marc marc 158104 Nov 13 03:27 _codecs_hk.cpython-35m-x86_64-linux-gnu.so
-rw-r--r--  1 marc marc  31128 Nov 13 03:27 _codecs_iso2022.cpython-35m-x86_64-linux-gnu.so
-rw-r--r--  1 marc marc 268664 Nov 13 03:27 _codecs_jp.cpython-35m-x86_64-linux-gnu.so
-rw-r--r--  1 marc marc 137592 Nov 13 03:27 _codecs_kr.cpython-35m-x86_64-linux-gnu.so
-rw-r--r--  1 marc marc 113016 Nov 13 03:27 _codecs_tw.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x  2 marc marc   4096 Mar 30 22:42 collections/
drwxrwxr-x  4 marc marc   4096 Mar 30 22:42 cryptography/
drwxr-xr-x  2 marc marc   4096 Mar 30 22:42 ctypes/
-rw-r--r--  1 marc marc 156624 Nov 13 03:27 _ctypes.cpython-35m-x86_64-linux-gnu.so
-rw-r--r--  1 marc marc 183008 Nov 13 03:27 _decimal.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x  3 marc marc   4096 Mar 30 22:42 email/
drwxr-xr-x  2 marc marc   4096 Mar 30 22:42 encodings/
-rw-r--r--  1 marc marc  29488 Nov 13 03:27 _hashlib.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x  2 marc marc   4096 Mar 30 22:42 html/
drwxr-xr-x  2 marc marc   4096 Mar 30 22:42 http/
drwxrwxr-x  2 marc marc   4096 Mar 30 22:42 idna/
drwxr-xr-x  2 marc marc   4096 Mar 30 22:42 importlib/
-rwxrwxr-x  1 marc marc 149064 Sep 23  2018 libffi-ae16d830.so.6.0.4*
-rw-rw-r--  1 marc marc 842274 Mar 30 22:45 library.zip
drwxr-xr-x  2 marc marc   4096 Mar 30 22:42 logging/
-rw-r--r--  1 marc marc  37616 Nov 13 03:27 _lzma.cpython-35m-x86_64-linux-gnu.so
-rw-r--r--  1 marc marc  44144 Nov 13 03:27 _multibytecodec.cpython-35m-x86_64-linux-gnu.so
-rw-r--r--  1 marc marc   6504 Nov 13 03:27 _opcode.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x  2 marc marc   4096 Mar 30 22:42 pydoc_data/
-rw-r--r--  1 marc marc  31688 Nov 13 03:27 readline.cpython-35m-x86_64-linux-gnu.so
-rw-r--r--  1 marc marc 118744 Nov 13 03:27 _ssl.cpython-35m-x86_64-linux-gnu.so
-rw-r--r--  1 marc marc  25032 Nov 13 03:27 termios.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x  2 marc marc   4096 Mar 30 22:42 unittest/
drwxr-xr-x  2 marc marc   4096 Mar 30 22:42 urllib/
drwxr-xr-x  6 marc marc   4096 Mar 30 22:42 xml/
```
What am I doing wrong? How can I fix this?

Marc.

**Comment by 1marc1** [comment] 2019-04-01 01:52
I found a workaround for this issue: copy `dist/lib/libffi-ae16d830.so.6.0.4` to the `dist/` directory and it will start working.

**Comment by marcelotduarte** [comment] 2019-07-21 06:01
Duplicate of #313

**Closed as completed** 2019-08-10 16:55 UTC

**Comment by rwuebker** [comment] 2019-09-12 02:44
Hi @anthony-tuininga I'm having a the exact error: `libffi-ae16d830.so.6.0.4: cannot open shared object file: No such file or directory` except it's in a python3 aws lambda. How did you solve this? I don't get the error if I use python2.7.

Thanks!
Rick

**Comment by marcelotduarte** [comment] 2019-09-12 03:27
This error will be resolved. There are two pending patches that will resolve this issue. When applied, I will inform you in issue #313.

**Comment by marcelotduarte** [comment] 2020-01-05 04:51
cx_Freeze 6.1 has just been released.
