### ISSUE TITLE
Code Signing windows Executable along with cx freeze.

### ISSUE THREAD

**Issue by mai1x9** [marcelotduarte/cx_Freeze#1553] opened 2022-07-16 09:35 UTC
I have a couple of questions on code signing the executable with cx freeze.
1. Does cx freeze **build** or **build_msi** support the automatic code signing by supplying the pfx file and pfx cert password. 
2. If I generate couple of exe files using cxfreeze (I have generated around 5 different exe's by defining in setup.py), do I need to sign all the executable files. Basically, executable1 will launch the other 4 executables using subprocess. Is it sufficient to sign only executable1, or do I need to sign all 4 executables.
3. Does a code signed executable (generated by cx freeze) will anti virus detect as suspicious program. ?

Any help would be great. 

@marcelotduarte

**Comment by marcelotduarte** [comment] 2022-07-16 16:10
Currently, a workaround is used. Please check #203

**Comment by marcelotduarte** [comment] 2023-02-19 19:11
Duplicate of #203

**Closed as completed by marcelotduarte** 2023-02-19 19:11 UTC
