### ISSUE TITLE
when using cx_Freeze.Freezer : missing 1 required positional argument: 'constantsModule'

### ISSUE THREAD

**Issue by hackery98** [marcelotduarte/cx_Freeze#563] opened 2020-01-06 09:30 UTC
https://github.com/anthony-tuininga/cx_Freeze/blob/6c1d6f23f401d40368d4fab5cd710a784b114a12/cx_Freeze/main.py#L165

__init__() missing 1 required positional argument: 'constantsModule'

**Comment by marcelotduarte** [comment] 2020-01-06 17:47
Duplicate of #560

**Closed as completed by marcelotduarte** 2020-01-06 17:47 UTC
