### ISSUE TITLE
why my program don't launch??

### ISSUE THREAD

**Issue by Mohammadwh** [marcelotduarte/cx_Freeze#644] opened 2020-04-28 07:42 UTC
hello guys
![1](https://user-images.githubusercontent.com/18552903/80460648-621e6b00-8949-11ea-8d18-e76c02aae259.PNG)
![2](https://user-images.githubusercontent.com/18552903/80460654-63e82e80-8949-11ea-8613-bc93ef3e800f.PNG)
i get this error in launch program and i don't import this libraries in my script :|

**Comment by marcelotduarte** [comment] 2020-04-28 10:07
Use setuptools < 45
A patch for this error exist and was merged. The next version will support setuptools >=45.
You don't import it, but imageio_ffmeg imports.

**Comment by marcelotduarte** [comment] 2020-04-28 10:09
Duplicate of #579

**Closed as completed by marcelotduarte** 2020-04-28 10:09 UTC
