### ISSUE TITLE
Numpy+MKL: ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by kiflowb777** [marcelotduarte/cx_Freeze#1110] opened 2021-06-15 12:43 UTC
**Desktop (please complete the following information):**
 - Platform information (e.g. Ubuntu Linux 16.04): Windows 10
 - OS architecture (e.g. amd64): 64bit
 - cx_Freeze version: 6.6
 - Python version [e.g. 3.9]: 3.6.1
 - Numpy: 1.19.5+mkl

After freezing my project with numpy+mkl I get:
```python
File "c:\python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 81, in run	__main__:48
	module.run()	__main__:48
File "c:\python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run	__main__:48
	exec(code, m.__dict__)	__main__:48
File "project.py", line 11, in <module>	__main__:48
File "D:\FROZEN_TARGET\lib\numpy\__init__.py", line 124, in <module>	__main__:48
	    from numpy.__config__ import show as show_config	__main__:48
source code string cannot contain null bytes	__main__:36

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 81, in run
    module.run()
  File "c:\python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
    exec(code, m.__dict__)
  File "project.py", line 11, in <module>
  File "D:\FROZEN_TARGET\lib\numpy\__init__.py", line 124, in <module>
    from numpy.__config__ import show as show_config
ValueError: source code string cannot contain null bytes
```

**Comment by kiflowb777** [comment] 2021-06-15 13:41
To fix it I have to move all *.dll files from ```D:\FROZEN_TARGET\lib\numpy\DLLs``` to ```D:\FROZEN_TARGET``` and then I can run my project.exe after freezing with cx_freeze.

If only copy all *.dll files then I get:
```OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.```

**Comment by kiflowb777** [comment] 2021-06-15 13:45
With cx-Freeze 6.7b5 the problem still exists.

**Comment by marcelotduarte** [comment] 2021-06-15 16:55
Is the D drive a network drive or a hard disk partition?

**Comment by kiflowb777** [comment] 2021-06-16 07:22
> 
> 
> Is the D drive a network drive or a hard disk partition?

The D is a hard disk partition.

**Comment by kiflowb777** [comment] 2021-06-16 07:26
Numpy+mkl was installed with pip and whl file (```numpy‑1.19.5+mkl‑cp36‑cp36m‑win_amd64.whl```) from: [https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy](url)

**Comment by marcelotduarte** [comment] 2021-06-16 07:40
I used a simple test at https://github.com/marcelotduarte/cx_Freeze/tree/main/cx_Freeze/samples/pandas
I tested it in the past with 3.8 and 3.9, using the numpy+mkl from the same site ( I think this is a duplicate of #739 that is partially resolved)
The test passes for me and for the issue reporter, but a real case fails, but have a workaround.
Can you test this sample?
I tested it with 3.6.8 and works too.

**Comment by marcelotduarte** [comment] 2021-06-16 07:41
![pandas+mkl+36](https://user-images.githubusercontent.com/12752334/122178657-24d2b080-ce5d-11eb-821e-d9919aa9c949.png)

**Comment by kiflowb777** [comment] 2021-06-16 10:11
```
PS C:\Users\kiflowb777\Documents\GitHub\cx_Freeze\cx_Freeze\samples\pandas\PANDA_TEST> .\test_pandas.exe
pandas version 1.1.5
          0         1         2         3   4
0       NaN       NaN       NaN       NaN NaN
1  0.017918       NaN       NaN       NaN NaN
2 -0.057913  0.001125       NaN       NaN NaN
3 -0.158868 -0.093881 -0.147052       NaN NaN
4  0.078993  0.001654 -0.041154 -0.041946 NaN
PS C:\Users\kiflowb777\Documents\GitHub\cx_Freeze\cx_Freeze\samples\pandas\PANDA_TEST>
```

**Comment by marcelotduarte** [comment] 2021-06-18 09:10
@kiflowb777 PR #1113 fix this issue.
Can you test the new beta release 6.7b6?
pip install --upgrade cx_Freeze --pre

**Comment by kiflowb777** [comment] 2021-06-21 07:55
With 6.7b6 I get:
```
INTEL MKL ERROR: The specified module could not be found. mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
```
but when copy file ```mkl_intel_thread.dll``` from ```D:\FROZEN_TARGET\lib\numpy_mkl``` to ```D:\FROZEN_TARGET``` it works.

**Comment by marcelotduarte** [comment] 2021-06-21 08:43
Can you upgrade your pip and setuptools to the latest version and force the reinstallation of some packages by uninstalling or using:
pip install --force --resintall package
use this to resintall cx_Freeze and numpy at least. And take a look at #793. You got the error that he has at v6.6...

**Comment by kiflowb777** [comment] 2021-06-21 09:54
I try with:
```batch
set PYTHON_DIR_PATH=C:\python36\freeze_venv\Scripts

%PYTHON_DIR_PATH%\python -m pip install --upgrade pip
%PYTHON_DIR_PATH%\python -m pip install --upgrade setuptools

%PYTHON_DIR_PATH%\python -m pip install --force-reinstall pip
%PYTHON_DIR_PATH%\python -m pip install --force-reinstall setuptools
%PYTHON_DIR_PATH%\python -m pip install --force-reinstall "D:\whls\numpy-1.19.5+mkl-cp36-cp36m-win_amd64.whl"
%PYTHON_DIR_PATH%\python -m pip install --force-reinstall cx-Freeze --pre
%PYTHON_DIR_PATH%\python -m pip list

set CXFREEZE_PATH=%PYTHON_DIR_PATH%\cxfreeze.exe
echo "%CXFREEZE_PATH%"
"%CXFREEZE_PATH%" -O -OO --target-dir=TF_TEST --target-name="hello.exe" hello.py > freeze.log
```

but still have:
```
INTEL MKL ERROR: The specified module could not be found. mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
```

**Comment by marcelotduarte** [comment] 2021-06-21 10:27
OK. I suspect something else, I'm waiting for a response from another developer and I'm going to make a new patch.

**Comment by marcelotduarte** [comment] 2021-06-23 19:54
I did a new PR #1125 and release cx_Freeze 6.7b7.
Can you test the new beta release?
pip install --upgrade cx_Freeze --pre

**Comment by kiflowb777** [comment] 2021-06-24 08:21
With version 6.7b7 I have:
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TEMP\\cxfreezecr6r9x4c\\py\\_vendored_packages\\apipkg-1.4.dist-info\\DESCRIPTION.rst'
```

**Comment by kiflowb777** [comment] 2021-06-24 08:23
```batch
D:\Tests\tf>"C:\python36\Scripts\cxfreeze.exe" -O -OO --target-dir=TF_TEST --target-name="hello_tf.exe" hello_tf.py  1>freeze.log
Traceback (most recent call last):
  File "C:\pythons\python361_raw\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\pythons\python361_raw\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python36\Scripts\cxfreeze.exe\__main__.py", line 7, in <module>
  File "c:\python36\lib\site-packages\cx_Freeze\cli.py", line 262, in main
    freezer.Freeze()
  File "c:\python36\lib\site-packages\cx_Freeze\freezer.py", line 592, in Freeze
    self._freeze_executable(executable)
  File "c:\python36\lib\site-packages\cx_Freeze\freezer.py", line 179, in _freeze_executable
    finder.IncludeFile(exe.main_script, exe.main_module_name)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 656, in IncludeFile
    module = self._load_module(name, path, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 455, in _load_module
    self._run_hook("load", module.name, module)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 552, in _run_hook
    method(self, *args)
  File "c:\python36\lib\site-packages\cx_Freeze\hooks.py", line 615, in load_numpy
    finder.IncludePackage("numpy")
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 691, in IncludePackage
    self._import_all_sub_modules(module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 225, in _import_all_sub_modules
    sub_module, deferred_imports, recursive
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 214, in _import_all_sub_modules
    sub_module_name, deferred_imports
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 336, in _internal_import_module
    parent_name, deferred_imports
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 598, in _scan_code
    deferred_imports,
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 161, in _ensure_from_list
    self._import_module(sub_module_name, deferred_imports, caller)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 620, in _scan_code
    constant, module, deferred_imports, top_level=False
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 598, in _scan_code
    deferred_imports,
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 161, in _ensure_from_list
    self._import_module(sub_module_name, deferred_imports, caller)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 620, in _scan_code
    constant, module, deferred_imports, top_level=False
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 620, in _scan_code
    constant, module, deferred_imports, top_level=False
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 598, in _scan_code
    deferred_imports,
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 161, in _ensure_from_list
    self._import_module(sub_module_name, deferred_imports, caller)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 295, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 462, in _load_module
    self._scan_code(module.code, module, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 620, in _scan_code
    constant, module, deferred_imports, top_level=False
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 620, in _scan_code
    constant, module, deferred_imports, top_level=False
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 586, in _scan_code
    name, deferred_imports, module, relative_import_index
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 261, in _import_module
    module = self._internal_import_module(name, deferred_imports)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 352, in _internal_import_module
    name, path, deferred_imports, parent_module
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 416, in _load_module
    module = self._add_module(name, path=path_list, parent=parent)
  File "c:\python36\lib\site-packages\cx_Freeze\finder.py", line 112, in _add_module
    rootcachedir=self.dist_cachedir.name,
  File "c:\python36\lib\site-packages\cx_Freeze\module.py", line 61, in __init__
    self.update_distribution(name)
  File "c:\python36\lib\site-packages\cx_Freeze\module.py", line 80, in update_distribution
    self._cache_dist_info(req_name)
  File "c:\python36\lib\site-packages\cx_Freeze\module.py", line 100, in _cache_dist_info
    shutil.copy2(src_path, dst_path)
  File "C:\pythons\python361_raw\lib\shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\pythons\python361_raw\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\TEMP\\cxfreezecr6r9x4c\\py\\_vendored_packages\\apipkg-1.4.dist-info\\DESCRIPTION.rst'
```

**Comment by marcelotduarte** [comment] 2021-07-07 02:21
cx_Freeze 6.7b8 has just been released.
pip install cx-Freeze==6.7b8

Try it out and confirm.

**Comment by kiflowb777** [comment] 2021-07-07 07:29
Thank you, with the latest version of cx-Freeze 6.7b8,  the Numpy+MKL package freezes correctly.

Example works:
```batch
PS D:\Freezing_test\tf\TF_TEST> .\hello_tf.exe
2021-07-07 09:20:30.617762: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
2021-07-07 09:20:32.746606: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library nvcuda.dll
2021-07-07 09:20:32.792647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.755GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2021-07-07 09:20:32.792772: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
2021-07-07 09:20:32.811751: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
2021-07-07 09:20:32.811867: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
2021-07-07 09:20:32.818921: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cufft64_10.dll
2021-07-07 09:20:32.821443: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library curand64_10.dll
2021-07-07 09:20:32.830064: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusolver64_11.dll
2021-07-07 09:20:32.835011: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusparse64_11.dll
2021-07-07 09:20:32.836465: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2021-07-07 09:20:32.836669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-07 09:20:32.837551: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-07 09:20:32.838602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.755GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2021-07-07 09:20:32.838746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-07 09:20:33.745825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-07 09:20:33.745947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2021-07-07 09:20:33.747739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2021-07-07 09:20:33.748426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3961 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
b'Hello, TensorFlow!'
PS D:\Freezing_test\tf\TF_TEST>
```

```batch
PS D:\Freezing_test\tf\TF_TEST> ls


    Directory: D:\Freezing_test\tf\TF_TEST


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        07.07.2021     09:19                lib
-a----        07.07.2021     09:17          13824 hello_tf.exe
-a----        06.07.2021     10:54          58008 python3.dll
-a----        06.07.2021     10:54        3562648 python36.dll


PS D:\Freezing_test\tf\TF_TEST>
```

**Comment by kiflowb777** [comment] 2021-07-07 07:44
```batch
PS D:\Freezing_test\panda_test\TF_TEST> .\test_panda.exe
pandas version 1.1.5
          0         1         2         3   4
0       NaN       NaN       NaN       NaN NaN
1 -0.113998       NaN       NaN       NaN NaN
2 -0.011313  0.152847       NaN       NaN NaN
3  0.075425  0.097777 -0.035758       NaN NaN
4 -0.061214 -0.054375  0.055756 -0.045954 NaN
PS D:\Freezing_test\panda_test\TF_TEST>
```

**Comment by marcelotduarte** [comment] 2021-07-09 00:05
cx_Freeze 6.7 has just been released.
pip install --upgrade cx_Freeze

**Closed as completed by marcelotduarte** 2021-07-09 00:05 UTC
Labels: patch available, success
