### ISSUE TITLE
Application runs only one time and then it cannot find a package

### ISSUE THREAD

**Issue by teodorwisniewski** [marcelotduarte/cx_Freeze#643] opened 2020-04-27 10:03 UTC
Hello Guys,
I have created a small app with Tkinter that allows to extract some data from selected Excel files and create a nice report. I want to share it with my colleagues. Thus, I decided to create an "exe" file out of my code. 
After building the app with the following "setup" file:

`from cx_Freeze import setup, Executable
import cx_Freeze as cx
import sys
import os

libs_to_include = ["tkinter","os",'csv',"pandas","xlwings","xlsxwriter","numpy","matplotlib.backends.backend_tkagg",
            "scipy.sparse.csgraph._validation","scipy"]

packages_to_include = ["tw_package"] + libs_to_include
libs_to_exclude = ['PyQt4', 'PyQt5', 'PySide', 'IPython','jupyter_client', 'jupyter_core', 'ipykernel','ipython_genutils',"scipy.spatial.cKDTree"]

include_files = [r"tw_package\resources"]
if platform.system() == "Windows":
    base = "Win32GUI"
    target_name = 'tw_app.exe'
    PYTHON_DIR = os.path.dirname(os.path.dirname(os.__file__))
    os.environ['TCL_LIBRARY'] = os.path.join(PYTHON_DIR, 'tcl', 'tcl8.6')
    os.environ['TK_LIBRARY'] = os.path.join(PYTHON_DIR, 'tcl', 'tk8.6')
    include_files += [
        (os.path.join(PYTHON_DIR, 'DLLs', 'tcl86t.dll'), ''),
        (os.path.join(PYTHON_DIR, 'DLLs', 'tk86t.dll'), '')
    ]

cx.setup(
    name='Tw_App',
    version='1.4',
    author='Teodor Wisniewski',
    description='Data driven applicatios',
    packages=['tw_package'],
    executables=[
        cx.Executable('main_app.py', base=base,
                      targetName=target_name)],
    options={
        'build_exe': {
            'packages': packages_to_include,
            'includes': libs_to_include,
            'excludes': libs_to_exclude,
            'include_files': include_files
        }
    }
)`

I can open my application one time and it works as I want, but as I relaunch the app, I get the following error:
![image](https://user-images.githubusercontent.com/48416342/80359640-63369600-887e-11ea-86c1-aa90bd644328.png)

Here is the structure of my project:

- main_app.py
- setup.py
- tw_package 
In the tw_package, there are other sub packages.

Do you have any ideas why my app cannot find this package? It works if I open it in my IDE.

**Comment by marcelotduarte** [comment] 2020-04-27 17:55
If your system is windows, python 3.7, cx-freeze 6.1, then:
- try to remove:
PYTHON_DIR = os.path.dirname(os.path.dirname(os.file))
os.environ['TCL_LIBRARY'] = os.path.join(PYTHON_DIR, 'tcl', 'tcl8.6')
os.environ['TK_LIBRARY'] = os.path.join(PYTHON_DIR, 'tcl', 'tk8.6')
include_files += [
(os.path.join(PYTHON_DIR, 'DLLs', 'tcl86t.dll'), ''),
(os.path.join(PYTHON_DIR, 'DLLs', 'tk86t.dll'), '')
]
cx-freeze take care of this.
- remove packages=['tw_package'] - only packages at build_exe is needed
- change include_files = [r"tw_package\resources"] to include_files = ["tw_package\\resources"] (I know that is valid, but I have a bug in the past with it, with \r or \n, and only to test and discard a possibility of error)
- and I imagine that you have a import platform before platform.system() == "Windows"

**Comment by teodorwisniewski** [comment] 2020-04-27 18:34
Thank for your quick reply Marcelo.
Unfortunately, after applying your recommendations, I get a new error:
```
  File "C:\Users\wisniewskit\AppData\Local\Programs\Python\Python37\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'TCL_LIBRARY'
```
And the exe file is not even created.

So I guess the following code, has to be included:
```
    PYTHON_DIR = os.path.dirname(os.path.dirname(os.__file__))
    os.environ['TCL_LIBRARY'] = os.path.join(PYTHON_DIR, 'tcl', 'tcl8.6')
    os.environ['TK_LIBRARY'] = os.path.join(PYTHON_DIR, 'tcl', 'tk8.6')
    include_files += [
        (os.path.join(PYTHON_DIR, 'DLLs', 'tcl86t.dll'), ''),
        (os.path.join(PYTHON_DIR, 'DLLs', 'tk86t.dll'), '')
    ]
```
With this code, it creates the exe file, which I can execute only once.
But, then, I still get the first error: ModuleNotFoundError. It does not find my package "tw_package".


Here is my last version of my setup.py file:
```
from cx_Freeze import setup, Executable
import cx_Freeze as cx
import sys
import os
import platform



libs_to_include = ["tkinter","os",'csv',"pandas","xlwings","xlsxwriter","numpy","matplotlib.backends.backend_tkagg",
            "scipy.sparse.csgraph._validation","scipy"]

packages_to_include =  libs_to_include + ["tw_package"]
libs_to_exclude = ['PyQt4', 'PyQt5', 'PySide', 'IPython','jupyter_client', 'jupyter_core', 'ipykernel','ipython_genutils',"scipy.spatial.cKDTree"]

include_files = ["tw_package\\resources"]
if platform.system() == "Windows":
    base = "Win32GUI"
    target_name = 'IRT_Extractor.exe'
    PYTHON_DIR = os.path.dirname(os.path.dirname(os.__file__))
    os.environ['TCL_LIBRARY'] = os.path.join(PYTHON_DIR, 'tcl', 'tcl8.6')
    os.environ['TK_LIBRARY'] = os.path.join(PYTHON_DIR, 'tcl', 'tk8.6')
    include_files += [
        (os.path.join(PYTHON_DIR, 'DLLs', 'tcl86t.dll'), ''),
        (os.path.join(PYTHON_DIR, 'DLLs', 'tk86t.dll'), '')
    ]



cx.setup(
    name='Tw_App',
    version='1.4',
    author='Teodor Wisniewski',
    description='Data driven applicatios',
    executables=[
        cx.Executable('main_app.py', base=base,
                      targetName=target_name)],
    options={
        'build_exe': {
            'packages': packages_to_include,
            'includes': libs_to_include,
            'excludes': libs_to_exclude,
            'include_files': include_files
        }
    }
)
```

**Comment by marcelotduarte** [comment] 2020-04-27 18:37
What version of cx-freeze?

**Comment by marcelotduarte** [comment] 2020-04-27 18:40
Try to build this sample in your system:
https://github.com/anthony-tuininga/cx_Freeze/tree/master/cx_Freeze/samples/Tkinter

**Comment by teodorwisniewski** [comment] 2020-04-27 19:13
> 
> 
> What version of cx-freeze?

I've checked the version of cx_freeze and I was at 5.1.  I installed the 6.1 version and right now I have:
system is windows, python 3.7, cx-freeze 6.1

I get another error:
![image](https://user-images.githubusercontent.com/48416342/80411040-d0bce380-88cb-11ea-8fbe-51b3d1ad5179.png)

It cannot find tkinter.

**Comment by marcelotduarte** [comment] 2020-04-27 20:06
This is easy ;-) I have a PR #576 merged that will solve this in the next release. For now, a workaround.
- remove that block about tkinter environs
- in your libs to exclude, add 'Tkinter'

**Comment by teodorwisniewski** [comment] 2020-04-28 06:41
Thank you for your precious time Marcelo!
I added "Tkinter" into libs to exclude. And I managed to create a "build" directory with its exe file. Here is the last version of my setup file:
```
from cx_Freeze import setup, Executable
import cx_Freeze as cx
import sys
import os
import platform

libs_to_include = ["os",'csv',"pandas","xlwings","xlsxwriter","numpy","matplotlib.backends.backend_tkagg",
            "scipy.sparse.csgraph._validation","scipy"]
packages_to_include =   ["tw_package"]
libs_to_exclude = ["Tkinter",'PyQt4', 'PyQt5', 'PySide', 'IPython','jupyter_client', 'jupyter_core', 'ipykernel','ipython_genutils',"scipy.spatial.cKDTree"]
include_files = ["tw_package\\resources"]

if platform.system() == "Windows":
    base = "Win32GUI"
    target_name = 'tw_app.exe'

cx.setup(
    name='Tw_App',
    version='1.4',
    author='Teodor Wisniewski',
    description='Data driven applicatios',
    executables=[
        cx.Executable('main_app.py', base=base,
                      targetName=target_name)],
    options={
        'build_exe': {
            'packages': packages_to_include,
            'includes': libs_to_include,
            'excludes': libs_to_exclude,
            'include_files': include_files
        }
    }
)
```

I can run my 'exe' file one time and it works as I wish. As I run it for the second time, it has hard time finding the package of my project: tw_package:

![image](https://user-images.githubusercontent.com/48416342/80453726-21aef500-8929-11ea-8e40-f2731e53859c.png)

**Comment by marcelotduarte** [comment] 2020-04-28 10:05
You already tried to include it in includes, or, in your case, include 'tw_package.application' to libs_to_include?
This module exist?

**Comment by teodorwisniewski** [comment] 2020-04-28 16:22
Ok, I included 'tw_package.application'  into my project:

```
from cx_Freeze import setup, Executable
import cx_Freeze as cx
import sys
import os
import platform

libs_to_include = ["os",'csv',"pandas","xlwings","xlsxwriter","numpy","matplotlib.backends.backend_tkagg",
            "scipy.sparse.csgraph._validation","scipy"]

packages_to_include =   ["tw_package.application"]
libs_to_exclude = ["Tkinter",'PyQt4', 'PyQt5', 'PySide', 'IPython','jupyter_client', 'jupyter_core', 'ipykernel','ipython_genutils',"scipy.spatial.cKDTree"]
include_files = ["tw_package\\resources"]

if platform.system() == "Windows":
    base = "Win32GUI"
    target_name = 'tw_app.exe'

cx.setup(
    name='Tw_App',
    version='1.4',
    author='Teodor Wisniewski',
    description='Data driven applicatios',
    executables=[
        cx.Executable('main_app.py', base=base,
                      targetName=target_name)],
    options={
        'build_exe': {
            'packages': packages_to_include,
            'includes': libs_to_include,
            'excludes': libs_to_exclude,
            'include_files': include_files
        }
    }
)
```
It allows to create the "built" directory:
![image](https://user-images.githubusercontent.com/48416342/80511836-f0f8ab00-897c-11ea-9288-0cd61ecd626b.png)

![image](https://user-images.githubusercontent.com/48416342/80511801-e2aa8f00-897c-11ea-92a5-daca120008fe.png)

I run it first time and I get what I want: 
![image](https://user-images.githubusercontent.com/48416342/80511641-a8d98880-897c-11ea-8b42-b7c4fd2e57ea.png)

I run it second time and I still get the same error: "no module tw_package.application":
![image](https://user-images.githubusercontent.com/48416342/80511723-c73f8400-897c-11ea-9df3-eec33da95ff8.png)

Here is the structure of my project:
![image](https://user-images.githubusercontent.com/48416342/80511129-fa354800-897b-11ea-89a0-040899127fc2.png)

Inside the "main_app.py", you find:
```
from tw_package.application import Application

app = Application()
app.mainloop()

```

Inside the tw_package, you can find following files and folders:
![image](https://user-images.githubusercontent.com/48416342/80511281-323c8b00-897c-11ea-8401-ab8865d22b05.png)

**Comment by marcelotduarte** [comment] 2020-04-28 16:31
Your 'packages': ["tw_package"] should be sufficient.
In 'excludes' add 'tw_package.Application' - it it the same error caused by Tkinter vs tkinter, ie, on Windows, this is the same name, for python packages it differs. Then your app can find Application as a module instead of a Class.

**Comment by teodorwisniewski** [comment] 2020-04-28 17:35
I introduced this modification:


```
libs_to_include = ["os",'csv',"pandas","xlwings","xlsxwriter","numpy","matplotlib.backends.backend_tkagg",
            "scipy.sparse.csgraph._validation","scipy"]

packages_to_include =   ["tw_package"]
libs_to_exclude = ["tw_package.Application","Tkinter",'PyQt4', 'PyQt5', 'PySide', 'IPython','jupyter_client', 'jupyter_core', 'ipykernel','ipython_genutils',"scipy.spatial.cKDTree"]
include_files = ["tw_package\\resources"]
```

and still the same error:
![image](https://user-images.githubusercontent.com/48416342/80518939-7a14df80-8987-11ea-9a89-b7a8a4b8b2f6.png)

**Comment by marcelotduarte** [comment] 2020-04-28 17:42
Compare if the names of files inside the tw_package and the generated at build\exe.....\lib\tw_package are different in case ("A" vs "a")

**Comment by teodorwisniewski** [comment] 2020-04-28 19:01
Finally, It works after 4 days of struggling, I did it thanks to you Marcelo!!! :-D 

As the code creates pdf, tex and Excel files , my code has to do some "cleaning" to remove all unnecessary data of project. It moves generated pdf files to the outputs folder, which is deleted at the beging of each report creation.  So the code as shown below moved all files except directories and "py" files to 'ouputs' directory. But as cx_freeze changes "py" files to "pyc" files. As a results, I moved the "application.pyc" files to "outputs" directory and it was no longer in tw_package directory.
```
    src_files = [filename for filename in src_files if (os.path.splitext(filename)[1] != '.py'
     and os.path.splitext(filename)[1] !=''
     and os.path.splitext(filename)[1] !='.pyc')]
    # copying results to outputs folder
    for file_name in src_files:
        # outputs_directory variable indicates where we want to copy our files
        full_file_name = os.path.join(main_directory, file_name) # it gives full absolute path to the directory
        if os.path.isfile(full_file_name):
            shutil.move(full_file_name, outputs_directory)
```

Thank you so much Marcelo!

**Comment by marcelotduarte** [comment] 2020-04-28 19:13
You can use zip_include_packages=["*"], zip_exclude_packages=[], so the files will by in library.zip

I'm glad I could help.

**Closed as completed by marcelotduarte** 2020-04-28 19:13 UTC
