### ISSUE TITLE
How to obfuscate Python Code with cx_Freeze? 

### ISSUE THREAD

**Issue by Hunter2809** [marcelotduarte/cx_Freeze#935] opened 2021-02-25 07:34 UTC
Hi!! 

I am a new user of cx_Freeze, and am using it to freeze a software I wanna distribute among other people... But I also don't wanna show the source code to other people... Soo is there a way to obfuscate the all the files of my Application, so that no one can see the Source Code???

**Comment by marcelotduarte** [comment] 2021-02-25 11:32
The distributed code is the bytecode, not the source code. But can be decompiled.
See more at #595 
Duplicate of #595

**Closed as completed by marcelotduarte** 2021-02-25 11:32 UTC
Labels: question
