### ISSUE TITLE
Trouble with Python3.9 on MacOS

### ISSUE THREAD

**Issue by michaeljones** [marcelotduarte/cx_Freeze#809] opened 2020-11-27 17:51 UTC
Thanks for the project. This is great!

I've encountered an issue whilst using Python 3.9 on MacOS. The `macdist.py` module uses deprecated methods here:

https://github.com/marcelotduarte/cx_Freeze/blob/a22daccccbe6986d294005f72a3a0fdb22371b6f/cx_Freeze/macdist.py#L186

and here:

https://github.com/marcelotduarte/cx_Freeze/blob/a22daccccbe6986d294005f72a3a0fdb22371b6f/cx_Freeze/macdist.py#L198

The [Python 3.8 plistlib docs](https://docs.python.org/3.8/library/plistlib.html) indicate that we should be using `load` and `dump` instead of `readPlist` and `writePlist`. The methods have been deprecated since Python 3.4 so they should be fine to use for the 3.6 to 3.9 compatibility that you are currently stating. I hope this all makes sense.

**Comment by marcelotduarte** [comment] 2020-11-27 19:40
Thanks for reporting.
Can you test my patch #810?
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@plist`

**Comment by michaeljones** [comment] 2020-11-27 20:47
I'll try to give it a shot tomorrow. Thanks for the quick work!

**Comment by michaeljones** [comment] 2020-11-28 14:58
With the current project that I'm working with I get:

```
  File "/Users/Michael/Library/Caches/pypoetry/virtualenvs/memory-kings-zAukBwiy-py3.9/lib/python3.9/site-packages/cx_Freeze/dist.py", line 260, in run
    freezer.Freeze()
  File "/Users/Michael/Library/Caches/pypoetry/virtualenvs/memory-kings-zAukBwiy-py3.9/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 807, in Freeze
    self._CopyFile(
  File "/Users/Michael/Library/Caches/pypoetry/virtualenvs/memory-kings-zAukBwiy-py3.9/lib/python3.9/site-packages/cx_Freeze/freezer.py", line 197, in _CopyFile
    newDarwinFile = DarwinFile(
  File "/Users/Michael/Library/Caches/pypoetry/virtualenvs/memory-kings-zAukBwiy-py3.9/lib/python3.9/site-packages/cx_Freeze/darwintools.py", line 92, in __init__
    if not _isMachOFile(path=self.originalFilePath):
  File "/Users/Michael/Library/Caches/pypoetry/virtualenvs/memory-kings-zAukBwiy-py3.9/lib/python3.9/site-packages/cx_Freeze/darwintools.py", line 28, in _isMachOFile
    if "Mach-O" in p.stdout.readline().decode():
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 131: invalid start byte
```
But I got that before and forgot to mention a change I already made.

If I change:
```python
    if "Mach-O" in p.stdout.readline().decode():
```
to:
```python
    if "Mach-O" in p.stdout.readline().decode(errors='ignore'):
```
Then it continues to the end of `python3 cx_setup.py bdist_dmg` and possibly succeeds. We still need to properly test the resulting dmg file. 

I realise that ignoring decoding errors is handly ideal but I'm not sure of the best way forward. I'm happy to try to provide more information if I can. When it fails with the above error, the path is to a `ttf` file 

If I run `file` on that path, I get:

```
$ file /Users/Michael/root/projects/memory_kings/fonts/dimbo_regular.ttf
/Users/Michael/root/projects/memory_kings/fonts/dimbo_regular.ttf: TrueType Font data, 14 tables, 1st "OS/2", 22 names, Macintosh,  2009, 2010, 2011, 2012 GrandChaos9000. Some Rights Reserved.Dimbo RegularVersion 2 - August 1
```

Not sure why this would be an issue.

So to clarify: I think your plist fix is working fine. Thank you for the quick turn around. But I'm also having this other issue which I don't understand which I've hacked around.

**Comment by marcelotduarte** [comment] 2020-11-28 19:27
_isMachOFile - Determines whether the file is a Mach-O file.
Do a test using a "try" in that code, because if it has errors I think it should return False, and, using ignore (maybe) it can return True.

**Comment by michaeljones** [comment] 2020-11-28 20:26
I'll give that a go and report back. Thanks!

**Comment by michaeljones** [comment] 2020-11-29 17:53
It builds ok with the `try` approach and returning `False` in the `except` but the final dmg doesn't open properly. It is a pygame-based game and the pygame window opens but then closes straight away. There is no reason to believe it is a cx_Freeze issue though. I'm not sure how to get some debug information or print outs from a dmg but I guess that is another quest :)

**Comment by marcelotduarte** [comment] 2020-11-29 23:43
ok
I'm preparing to get Github Actions to test cx-freeze on macOS, and found a bug (PR #812)
Can you test it with your project to test?
The branch develop has 3 PR ahead of master - 810, 811, 812.
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Comment by michaeljones** [comment] 2020-11-30 21:11
If I install that, I still have the `if "Mach-O" in p.stdout.readline().decode():` error that I mentioned above. If I do the `errors='ignore'` thing again then the rest of the build goes through fine. 

So it looks good? I guess? :)

**Comment by marcelotduarte** [comment] 2020-12-01 07:05
I remembered that this decode error had already been solved before, so there was a regression.
I made a new fix PR #816 
Can you test it?
(PR 810 is now in the master and 811,812 and 816 in develop).
`pip uninstall -y cx_Freeze`
`pip install git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Comment by marcelotduarte** [comment] 2020-12-01 07:10
I need to check if PR #812 does not cause regression on systems different from GA.
Can you show me the result of this command on your system?

`python -c "import distutils.sysconfig as ds; from pprint import pprint as p; p(ds.get_config_vars())"`

**Comment by michaeljones** [comment] 2020-12-01 21:44
I might be reading the graph wrong but I don't think the decode fix is merged into develop yet.

**Comment by michaeljones** [comment] 2020-12-01 21:46
[config.txt](https://github.com/marcelotduarte/cx_Freeze/files/5625615/config.txt)

This is the result of the `disutils.sysconfig` command above.

**Comment by marcelotduarte** [comment] 2020-12-01 22:23
> I don't think the decode fix is merged into develop yet.

Now it is merged.

**Comment by michaeljones** [comment] 2020-12-02 17:05
`python cx_setup.py build_dmg` has gone through successfully with a uninstall and then install of the `develop` branch. 

The game in the final `dmg` sadly still has loading issues but that is something else to debug and possibly not the fault of cx_Freeze.

Thanks for addressing the issues!

**Comment by marcelotduarte** [comment] 2020-12-05 18:04
cx_Freeze 6.4.2 has just been released.

**Comment by marcelotduarte** [comment] 2020-12-08 12:25
I'm closing this issue. Please feel free to open a new issue if you have new trouble.

**Closed as completed by marcelotduarte** 2020-12-08 12:25 UTC
