### ISSUE TITLE
Error when using `cx_freeze run app.py`: KeyError: 'IMPORT_STAR'

### ISSUE THREAD

**Issue by EnzoBustos** [marcelotduarte/cx_Freeze#2152] opened 2023-12-03 01:42 UTC
I'm trying to create an exe file from a streamlit app, so I create an wrapping code `run.py` as follows:

```import openpyxl
import pandas as pd
from datetime import datetime
from pytz import timezone
import os
import smtplib, ssl
import streamlit as st
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from PIL import Image

import subprocess

if __name__ == '__main__':
    subprocess.run("streamlit run app.py")
```

This above code is called `run.py` and it wraps my streamlit project, but I'm getting the following error when I use `cxfreeze -c run.py `:

```Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\guido\Downloads\MailAscoli\.venv\Scripts\cxfreeze.exe\__main__.py", line 4, in <module>
  File "C:\Users\guido\Downloads\MailAscoli\.venv\Lib\site-packages\cx_Freeze\__init__.py", line 12, in <module>
    from .command.build_exe import BuildEXE as build_exe
  File "C:\Users\guido\Downloads\MailAscoli\.venv\Lib\site-packages\cx_Freeze\command\build_exe.py", line 13, in <module>
    from cx_Freeze.freezer import Freezer
  File "C:\Users\guido\Downloads\MailAscoli\.venv\Lib\site-packages\cx_Freeze\freezer.py", line 30, in <module>
    from .finder import ModuleFinder
  File "C:\Users\guido\Downloads\MailAscoli\.venv\Lib\site-packages\cx_Freeze\finder.py", line 33, in <module>
    IMPORT_STAR = opcode.opmap["IMPORT_STAR"]
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'IMPORT_STAR'
```

**Comment by marcelotduarte** [comment] 2023-12-03 01:46
Duplicate of #1921 

cx_Freeze 6.15.x and dependencies (cx_Logging, Lief) are not declared compatible with Python 3.12 and do not provide wheels.

But, you can test the latest development build:
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`
For conda-forge the command is:
`conda install -y --no-channel-priority -S -c https://marcelotduarte.github.io/packages/conda cx_Freeze`

**Closed as completed by marcelotduarte** 2023-12-03 01:46 UTC
