### ISSUE TITLE
Error while freezing pandastable , AttributeError: module 'zmq' has no attribute 'libzmq'

### ISSUE THREAD

**Issue by Venoob** [marcelotduarte/cx_Freeze#947] opened 2021-03-01 06:29 UTC
I' am using anaconda 3,
Pyhon version : 3.8.5
I try to freeze my app but it returns AttributeError: module 'zmq' has no attribute 'libzmq':
here is the trackback:

  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 568, in _scan_
code
    self._ensure_from_list(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 152, in _ensur
e_from_list
    self._import_module(sub_module_name, deferred_imports, caller)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 593, in _scan_
code
    self._scan_code(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 429, in _load_
module
    self._run_hook("load", module.name, module)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 526, in _run_h
ook
    method(self, *args)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\hooks.py", line 1103, in load_s
etuptools
    finder.IncludePackage("setuptools")
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 649, in Includ
ePackage
    self._import_all_sub_modules(module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 215, in _impor
t_all_sub_modules
    self._import_all_sub_modules(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 204, in _impor
t_all_sub_modules
    sub_module = self._internal_import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 325, in _inter
nal_import_module
    parent_module = self._internal_import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 325, in _inter
nal_import_module
    parent_module = self._internal_import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 593, in _scan_
code
    self._scan_code(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 286, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 325, in _inter
nal_import_module
    parent_module = self._internal_import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 286, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 593, in _scan_
code
    self._scan_code(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 568, in _scan_
code
    self._ensure_from_list(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 152, in _ensur
e_from_list
    self._import_module(sub_module_name, deferred_imports, caller)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 568, in _scan_
code
    self._ensure_from_list(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 152, in _ensur
e_from_list
    self._import_module(sub_module_name, deferred_imports, caller)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 593, in _scan_
code
    self._scan_code(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 593, in _scan_
code
    self._scan_code(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 325, in _inter
nal_import_module
    parent_module = self._internal_import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 325, in _inter
nal_import_module
    parent_module = self._internal_import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 286, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 286, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 436, in _load_
module
    self._scan_code(module.code, module, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 559, in _scan_
code
    imported_module = self._import_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 252, in _impor
t_module
    module = self._internal_import_module(name, deferred_imports)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 341, in _inter
nal_import_module
    module = self._load_module(
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 429, in _load_
module
    self._run_hook("load", module.name, module)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\finder.py", line 526, in _run_h
ook
    method(self, *args)
  File "C:\anaconda3\lib\site-packages\cx_Freeze\hooks.py", line 1325, in load_z
mq
    libzmq = __import__("zmq", fromlist=["libzmq"]).libzmq
AttributeError: module 'zmq' has no attribute 'libzmq'

**Comment by marcelotduarte** [comment] 2021-03-01 13:45
Duplicate of #919
See comment: https://github.com/marcelotduarte/cx_Freeze/issues/919#issuecomment-781056204

**Closed as completed** 2021-03-01 14:12 UTC

**Comment by marcelotduarte** [comment] 2021-04-14 11:13
cx_Freeze 6.6 has just been released.
