### ISSUE TITLE
Multiprocessing Pool problem (5.x  / 6.0b1)

### ISSUE THREAD

**Issue by PhilHay** [marcelotduarte/cx_Freeze#391] opened 2018-06-26 14:07 UTC
Hello,

what was solved for Process.py still does not work for Pool.py.
There is also here a class Pool and a module pool.
cx_Freeze create a file lib/multiprocessing/Pool.py instead of pool.py (lower case).

This could be solved by adding this line in hooks.py:
9)    finder.ExcludeModule("multiprocessing.Process")
10)  finder.ExcludeModule("multiprocessing.Pool")  # New code

Thanks

**Comment by marcelotduarte** [comment] 2020-02-14 18:17
Duplicate of #353

**Closed as completed by marcelotduarte** 2020-02-14 18:17 UTC
