### ISSUE TITLE
In macos. Packaged with [Chinese name.app] cannot run. When it was running, it started and it just exited.

### ISSUE THREAD

**Issue by fushun1990** [marcelotduarte/cx_Freeze#2212] opened 2024-01-22 12:17 UTC
In macos. Packaged with [Chinese name.app] cannot run. When it was running, it started and it just exited.

在macos中。使用【中文名称.app】打包的不能运行。运行的时候时候启动就直接退出了。

**Screenshots**

https://github.com/marcelotduarte/cx_Freeze/assets/10917744/0a3c2e37-707a-4009-b99a-8b1af19d7ab5
![image](https://github.com/marcelotduarte/cx_Freeze/assets/10917744/aaeeac9e-955d-423a-a084-ad7daa6e976c)
![image](https://github.com/marcelotduarte/cx_Freeze/assets/10917744/6c443ace-c1b7-4e26-bbe1-a950295da368)

**Desktop (please complete the following information):**
macOS Sonoma 版本14.0
Python 3.10.13
cx-Freeze  6.15.12
PyQt5                                             5.15.10
PyQt5-Qt5                                         5.15.12
PyQt5-sip                                         12.13.0

**Additional context**

This is sample code from sample/pyqt5

使用的就是sample/pyqt5的示例代码

**Comment by marcelotduarte** [comment] 2024-01-22 16:26
Please check if this issue is duplicate of #1228

**Comment by fushun1990** [comment] 2024-01-23 03:18
> Please check if this issue is duplicate of #1228
![image](https://github.com/marcelotduarte/cx_Freeze/assets/10917744/ece006d5-2599-4cdd-ae96-b808cd47aeb7)

No, I use open Hello. The app works
不, 我使用 open 你好.app 可以正常运行

**Comment by fushun1990** [comment] 2024-01-26 09:42
@marcelotduarte

**Comment by marcelotduarte** [comment] 2024-01-31 04:38
Let me see if I got it. If you use sample/pyqt5 without modifications, you compile it and can run it. But if you change and use Chinese characters in the name or bundle_name, then you can't execute it?

EDIT:
https://github.com/marcelotduarte/cx_Freeze/blob/main/cx_Freeze/hooks/pyqt5/_append_to_init.py#L10

**Comment by fushun1990** [comment] 2024-01-31 06:30
yes

**Comment by fushun1990** [comment] 2024-01-31 06:34
我的需求是，将应用打包为中文名称的app应用。并不一定需要将`hello.py`文件修改为`您好.py`

My requirement is to package the application as an app with a Chinese name. It's not necessary to change 'hello.py' to '你好.py'

**Comment by fushun1990** [comment] 2024-02-01 13:44
@marcelotduarte

**Comment by marcelotduarte** [comment] 2024-05-09 21:51
Recently when implementing a patch, I had to deal with the utf8 name situation. See if it resolved it for you.
I even tested it with Chinese characters [here](https://github.com/marcelotduarte/cx_Freeze/pull/2379/files#diff-473ce9a51e7b6034a5f2d429ecb0d7c6e91525d33c14c20ccc0cfbd1be085d59R319).

You can test the patch in the latest development build:
`pip install --force --no-cache --pre --extra-index-url https://marcelotduarte.github.io/packages/ cx_Freeze`

Please give me feedback.

**Comment by marcelotduarte** [comment] 2024-05-29 01:33
[Release 7.1.0](https://github.com/marcelotduarte/cx_Freeze/releases/tag/7.1.0) is out!
[Documentation](https://cx-freeze.readthedocs.io)

@fushun1990 Can you test and give me feedback?

**Closed as completed** 2024-09-23 02:07 UTC
Labels: Waiting User Feedback
