### ISSUE TITLE
Win10 Py3.6 cx-freeze6.1 , error"__init__() missing 1 required positional argument: 'constantsModule'"

### ISSUE THREAD

**Issue by luxjn** [marcelotduarte/cx_Freeze#597] opened 2020-02-26 15:52 UTC
My OS is Win10, use py3.6 and cx-freeze 6.1

cxfreeze my\path\my.py --target-dir my\target\path

this is the issue
===========================================
Traceback (most recent call last):
  File "e:\program files\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\program files\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Program Files\Python\Python36\Scripts\cxfreeze.exe\__main__.py", line 7, in <module>
  File "e:\program files\python\python36\lib\site-packages\cx_Freeze\main.py", line 174, in main
    silent = options.silent)
TypeError: __init__() missing 1 required positional argument: 'constantsModule'
============================================

what did I miss?

**Comment by marcelotduarte** [comment] 2020-02-26 15:57
Duplicate of #560

**Closed as completed by marcelotduarte** 2020-02-26 15:57 UTC
