### ISSUE TITLE
VirusTotal false positive when adding an icon to Windows generated exe

### ISSUE THREAD

**Issue by skonet** [marcelotduarte/cx_Freeze#1059] opened 2021-05-16 16:53 UTC
Hello,

First I must say, that cx_Freeze is a good tool and I appreciate it much!

I use latest version with Python 3.9.4 (64bit) on a Win10 (64bit) PC.
Since I want to generate two exe files from two Python programs in the same file tree, I use setup.py instead of cx-freeze script, but I could get the same issue from cx-freeze script as well.

After some research and many tests, here is what I observed:
- If I generate exe file with cx_Freeze with no icon attached, the exe file works and gets through VirusTotal with no virus found
- If I add an icon to the exe file, the exe file still works, but VirusTotal finds a virus!
- If I add the same icon with another tool (ResourceHacker) after exe generation, VirusTotal finds no virus!

I attach the used ico file (in a zip) to help you diagnose.
[ddv.zip](https://github.com/marcelotduarte/cx_Freeze/files/6489608/ddv.zip)

Hopefully this may help you to improve the tool :-)

Best regards,
Steph.

**Comment by marcelotduarte** [comment] 2021-05-17 20:57
Duplicate of #315
Are you using base Console or Win32GUI?
Do you have downloaded Python from python.org?
Can you post the link to the results?

**Comment by skonet** [comment] 2021-05-18 20:48
Hello,

Not sure it is a duplicate of #315, conditions seem to be a little different: only adding an icon provokes the exe to be detected as a malware by VirusTotal.

Console is used as base and Python was downloaded from python.org.

I cannot upload the exe since it is detected as malware :-(
But here is a zip containing code to reprodue the issue: [ddv_outils.zip](https://github.com/marcelotduarte/cx_Freeze/files/6504347/ddv_outils.zip)

Steph.

**Comment by marcelotduarte** [comment] 2021-05-18 21:35
I think it s a duplicate, but you discovered that the cause is the added icon. With this information, I found that when the icon is added, the PE checksum should be updated too.
I used [Pepper](https://github.com/jovibor/Pepper/tree/master/Pepper) to see the checksum.

**Comment by marcelotduarte** [comment] 2021-05-24 01:06
I created an extension function to update the PE checksum. I discovered that with MSVC installed in GitHub CI generates a zero checksum. In my machine with Mingw the checksum is correct, but if I add an icon, it should be updated, so this function fix it in all cases.
I released a new beta, please try it out.
pip install cx-Freeze==6.7b1

**Comment by marcelotduarte** [comment] 2021-05-25 15:41
cx_Freeze 6.7b2 has just been released.
pip install cx-Freeze==6.7b2
Assuming this has been resolved.
If you had issues please open a new issue.

**Closed as completed by marcelotduarte** 2021-05-25 15:41 UTC
Labels: patch available

**Comment by marcelotduarte** [comment] 2021-07-09 12:35
cx_Freeze 6.7 has just been released.
