### ISSUE TITLE
Platform plugins not included into package [Anaconda]

### ISSUE THREAD

**Issue by Winand** [marcelotduarte/cx_Freeze#631] opened 2020-04-13 09:24 UTC
Related to #339. cx_Freeze cannot find Anaconda's platforms folder.

- Windows 7 x64
- Anaconda
- cx_Freeze 6.1
- Python 3.7.6
- PyQt 5.9.2

After some investigation I've found out that I have to initialize `QCoreApplication` manually during the building process so `cx_freeze.hooks.copy_qt_plugins` can find plugins directory within `QCoreApplication.libraryPaths`, which is empty otherwise.

```
from qtpy import QtCore
# otherwise `cx_freeze.hooks.copy_qt_plugins` will not find plugins folder
_ = QtCore.QCoreApplication([])
print("Qt library paths:", _.libraryPaths())
```
P. S. But the created package is bloated with duplicate files, e.g. icudt58.dll (25MB) is copied not only into `lib`, but also `imageformats` and `platforms` directories.
upd: i see, it's issue 366

**Comment by thierryBottaro** [comment] 2020-07-16 13:29
I have the same problem... but your solution did not solve my problem.
I added 
```
# otherwise `cx_freeze.hooks.copy_qt_plugins` will not find plugins folder
_ = QtCore.QCoreApplication([])
print("Qt library paths:", _.libraryPaths())
```
I still get : "This application failed to start because it could not find or load the Qt platform plugin "windows"
in ""."

**Comment by Winand** [comment] 2020-07-16 16:22
You've added these lines into a building script or your program? I call these lines during the building process.

**Comment by thierryBottaro** [comment] 2020-07-17 08:26
You are right ! https://github.com/Odoth/pyqt5-template works now with your trick added in the building script (build.py)
Thanks a lot !

**Comment by marcelotduarte** [comment] 2021-04-14 10:46
cx_Freeze 6.6 has just been released.
Assuming this has been resolved.
If you had issues please open a new issue.

**Comment by marcelotduarte** [comment] 2021-07-15 21:49
I confirmed this issue. I'll work on a solution.
@Winand Your comments in #718 and here helped to see the problem. Do you have the same version of pyqt?
I tested with the current of conda-forge pyqt 5.12.3
CC @thierryBottaro

**Comment by marcelotduarte** [comment] 2021-07-19 17:17
cx_Freeze 6.8b1 has just been released with fixes for pyqt5. Please, try it out and report.
pip install cx-Freeze==6.8b1

**Comment by marcelotduarte** [comment] 2021-08-16 11:55
[cx_Freeze 6.8b2](https://github.com/marcelotduarte/cx_Freeze/releases/tag/6.8b2) has just been released.
Please, try it out and report.
pip install cx-Freeze==6.8b2

**Comment by marcelotduarte** [comment] 2021-09-07 06:32
cx_Freeze 6.8 has just been released.
pip install --upgrade cx_Freeze
Assuming this has been resolved.
If you had issues please open a new issue.

**Closed as completed by marcelotduarte** 2021-09-07 06:32 UTC
Labels: patch available
