### ISSUE TITLE
numpy: Dll load failed while importing _cyptes(python3.8)

### ISSUE THREAD

**Issue by jekoie** [marcelotduarte/cx_Freeze#535] opened 2019-12-05 10:48 UTC
i build on python3.7 is ok, but on python3.8, it show:
![1](https://user-images.githubusercontent.com/6836400/70228508-6cb84800-178f-11ea-8a4d-f184fb74eca2.png)

**Comment by marcelotduarte** [comment] 2019-12-05 11:38
Duplicate of #523

**Closed as completed by marcelotduarte** 2019-12-05 11:38 UTC
