### ISSUE TITLE
can't install on python3.8?

### ISSUE THREAD

**Issue by jekoie** [marcelotduarte/cx_Freeze#534] opened 2019-12-05 00:53 UTC
I install it on python3.8, but it show errors?
```
$ python -m pip install cx_Freeze --upgrade
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting cx_Freeze
  Downloading https://mirrors.aliyun.com/pypi/packages/14/74/a76c12e4e357c79999191d5db259e66b46c57708515395c023d38e6bbbd7/cx_Freeze-6.0.tar.gz (88kB)
Installing collected packages: cx-Freeze
  Running setup.py install for cx-Freeze: started
    Running setup.py install for cx-Freeze: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jett chen\\AppData\\Local\\Temp\\pip-install-x3o8slng\\cx-Freeze\\setup.py'"'"'; __file__='"'"'C:\\Users\\jett chen\\AppData\\Local\\Temp\\pip-install-x3o8slng\\cx-Freeze\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jett chen\AppData\Local\Temp\pip-record-7r02taoy\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\jett chen\AppData\Local\Temp\pip-install-x3o8slng\cx-Freeze\
    Complete output (95 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\cx_Freeze
    copying cx_Freeze\common.py -> build\lib.win32-3.8\cx_Freeze
    copying cx_Freeze\dist.py -> build\lib.win32-3.8\cx_Freeze
    copying cx_Freeze\finder.py -> build\lib.win32-3.8\cx_Freeze
    copying cx_Freeze\freezer.py -> build\lib.win32-3.8\cx_Freeze
    copying cx_Freeze\hooks.py -> build\lib.win32-3.8\cx_Freeze
    copying cx_Freeze\macdist.py -> build\lib.win32-3.8\cx_Freeze
    copying cx_Freeze\main.py -> build\lib.win32-3.8\cx_Freeze
    copying cx_Freeze\setupwriter.py -> build\lib.win32-3.8\cx_Freeze
    copying cx_Freeze\windist.py -> build\lib.win32-3.8\cx_Freeze
    copying cx_Freeze\__init__.py -> build\lib.win32-3.8\cx_Freeze
    creating build\lib.win32-3.8\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\Console.py -> build\lib.win32-3.8\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\ConsoleSetLibPath.py -> build\lib.win32-3.8\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\SharedLib.py -> build\lib.win32-3.8\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\SharedLibSource.py -> build\lib.win32-3.8\cx_Freeze\initscripts
    copying cx_Freeze\initscripts\__startup__.py -> build\lib.win32-3.8\cx_Freeze\initscripts
    creating build\lib.win32-3.8\cx_Freeze\samples
    creating build\lib.win32-3.8\cx_Freeze\samples\advanced
    copying cx_Freeze\samples\advanced\advanced_1.py -> build\lib.win32-3.8\cx_Freeze\samples\advanced
    copying cx_Freeze\samples\advanced\advanced_2.py -> build\lib.win32-3.8\cx_Freeze\samples\advanced
    copying cx_Freeze\samples\advanced\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\advanced
    creating build\lib.win32-3.8\cx_Freeze\samples\asmodule
    copying cx_Freeze\samples\asmodule\asmodule.py -> build\lib.win32-3.8\cx_Freeze\samples\asmodule
    copying cx_Freeze\samples\asmodule\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\asmodule
    creating build\lib.win32-3.8\cx_Freeze\samples\importlib
    copying cx_Freeze\samples\importlib\get_examples.py -> build\lib.win32-3.8\cx_Freeze\samples\importlib
    copying cx_Freeze\samples\importlib\server_simple.py -> build\lib.win32-3.8\cx_Freeze\samples\importlib
    copying cx_Freeze\samples\importlib\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\importlib
    copying cx_Freeze\samples\importlib\web_srv.py -> build\lib.win32-3.8\cx_Freeze\samples\importlib
    copying cx_Freeze\samples\importlib\wsgiserver.py -> build\lib.win32-3.8\cx_Freeze\samples\importlib
    creating build\lib.win32-3.8\cx_Freeze\samples\matplotlib
    copying cx_Freeze\samples\matplotlib\matplotlib_eg.py -> build\lib.win32-3.8\cx_Freeze\samples\matplotlib
    copying cx_Freeze\samples\matplotlib\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\matplotlib
    creating build\lib.win32-3.8\cx_Freeze\samples\openpyxl
    copying cx_Freeze\samples\openpyxl\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\openpyxl
    copying cx_Freeze\samples\openpyxl\test_openpyxl.py -> build\lib.win32-3.8\cx_Freeze\samples\openpyxl
    creating build\lib.win32-3.8\cx_Freeze\samples\PyQt4
    copying cx_Freeze\samples\PyQt4\PyQt4app.py -> build\lib.win32-3.8\cx_Freeze\samples\PyQt4
    copying cx_Freeze\samples\PyQt4\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\PyQt4
    creating build\lib.win32-3.8\cx_Freeze\samples\PyQt5
    copying cx_Freeze\samples\PyQt5\PyQt5app.py -> build\lib.win32-3.8\cx_Freeze\samples\PyQt5
    copying cx_Freeze\samples\PyQt5\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\PyQt5
    creating build\lib.win32-3.8\cx_Freeze\samples\relimport
    copying cx_Freeze\samples\relimport\relimport.py -> build\lib.win32-3.8\cx_Freeze\samples\relimport
    copying cx_Freeze\samples\relimport\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\relimport
    creating build\lib.win32-3.8\cx_Freeze\samples\service
    copying cx_Freeze\samples\service\Config.py -> build\lib.win32-3.8\cx_Freeze\samples\service
    copying cx_Freeze\samples\service\ServiceHandler.py -> build\lib.win32-3.8\cx_Freeze\samples\service
    copying cx_Freeze\samples\service\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\service
    creating build\lib.win32-3.8\cx_Freeze\samples\simple
    copying cx_Freeze\samples\simple\hello.py -> build\lib.win32-3.8\cx_Freeze\samples\simple
    copying cx_Freeze\samples\simple\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\simple
    creating build\lib.win32-3.8\cx_Freeze\samples\Tkinter
    copying cx_Freeze\samples\Tkinter\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\Tkinter
    copying cx_Freeze\samples\Tkinter\SimpleTkApp.py -> build\lib.win32-3.8\cx_Freeze\samples\Tkinter
    creating build\lib.win32-3.8\cx_Freeze\samples\wx
    copying cx_Freeze\samples\wx\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\wx
    copying cx_Freeze\samples\wx\wxapp.py -> build\lib.win32-3.8\cx_Freeze\samples\wx
    creating build\lib.win32-3.8\cx_Freeze\samples\zope
    copying cx_Freeze\samples\zope\qotd.py -> build\lib.win32-3.8\cx_Freeze\samples\zope
    copying cx_Freeze\samples\zope\setup.py -> build\lib.win32-3.8\cx_Freeze\samples\zope
    running build_ext
    building 'cx_Freeze.util' extension
    creating build\temp.win32-3.8
    creating build\temp.win32-3.8\Release
    creating build\temp.win32-3.8\Release\source
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\include" "-IC:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsource/util.c /Fobuild\temp.win32-3.8\Release\source/util.obj
    util.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\libs" "/LIBPATH:C:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\PCbuild\win32" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x86" imagehlp.lib Shlwapi.lib /EXPORT:PyInit_util build\temp.win32-3.8\Release\source/util.obj /OUT:build\lib.win32-3.8\cx_Freeze\util.cp38-win32.pyd /IMPLIB:build\temp.win32-3.8\Release\source\util.cp38-win32.lib
      ▒▒▒ڴ▒▒▒▒▒ build\temp.win32-3.8\Release\source\util.cp38-win32.lib ▒Ͷ▒▒▒ build\temp.win32-3.8\Release\source\util.cp38-win32.exp
    ▒▒▒▒▒▒▒ɴ▒▒▒
    ▒▒▒▒ɴ▒▒▒▒▒▒▒▒
    creating build\temp.win32-3.8\Release\source\bases
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\include" "-IC:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsource/bases/Console.c /Fobuild\temp.win32-3.8\Release\source/bases/Console.obj
    Console.c
    creating C:\Users\jett chen\AppData\Local\Temp\pip-install-x3o8slng\cx-Freeze\build\lib.win32-3.8\cx_Freeze\bases
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 "/LIBPATH:C:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\libs" "/LIBPATH:C:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\PCbuild\win32" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x86" imagehlp.lib Shlwapi.lib build\temp.win32-3.8\Release\source/bases/Console.obj /OUT:build\lib.win32-3.8\cx_Freeze\bases\Console.exe /MANIFEST
    ▒▒▒▒▒▒▒ɴ▒▒▒
    ▒▒▒▒ɴ▒▒▒▒▒▒▒▒
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\include" "-IC:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsource/bases/Win32GUI.c /Fobuild\temp.win32-3.8\Release\source/bases/Win32GUI.obj
    Win32GUI.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 "/LIBPATH:C:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\libs" "/LIBPATH:C:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\PCbuild\win32" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x86" imagehlp.lib Shlwapi.lib user32.lib build\temp.win32-3.8\Release\source/bases/Win32GUI.obj /OUT:build\lib.win32-3.8\cx_Freeze\bases\Win32GUI.exe /MANIFEST
    ▒▒▒▒▒▒▒ɴ▒▒▒
    ▒▒▒▒ɴ▒▒▒▒▒▒▒▒
    running build_scripts
    creating build\scripts-3.8
    copying and adjusting cxfreeze -> build\scripts-3.8
    copying and adjusting cxfreeze-quickstart -> build\scripts-3.8
    error: file 'C:\Users\jett chen\AppData\Local\Temp\pip-install-x3o8slng\cx-Freeze\cxfreeze-postinstall' does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\jett chen\AppData\Local\Programs\Python\Python38_32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jett chen\\AppData\\Local\\Temp\\pip-install-x3o8slng\\cx-Freeze\\setup.py'"'"'; __file__='"'"'C:\\Users\\jett chen\\AppData\\Local\\Temp\\pip-install-x3o8slng\\cx-Freeze\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jett chen\AppData\Local\Temp\pip-record-7r02taoy\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

```

**Comment by marcelotduarte** [comment] 2019-12-05 11:22
PR #511 solve this. Can you try it with current master?

pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master

**Comment by kristofmulier** [comment] 2019-12-06 09:12
I had the same problem.
I tried your suggestion:

```sh
pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master
```
and now it works:

```sh
C:\Users\Kristof>cxfreeze
'cxfreeze' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Kristof>pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git@master
Collecting git+https://github.com/anthony-tuininga/cx_Freeze.git@master
  Cloning https://github.com/anthony-tuininga/cx_Freeze.git (to revision master) to c:\users\kristof\appdata\local\temp\pip-req-build-7hrolrl1
  Running command git clone -q https://github.com/anthony-tuininga/cx_Freeze.git 'C:\Users\Kristof\AppData\Local\Temp\pip-req-build-7hrolrl1'
Building wheels for collected packages: cx-Freeze
  Building wheel for cx-Freeze (setup.py) ... done
  Created wheel for cx-Freeze: filename=cx_Freeze-6.1-cp38-cp38-win_amd64.whl size=173005 sha256=507c3b90a1b7945fc277ccf25a5e4be7c64a37e1a1f6bce3f5171434c823fc04
  Stored in directory: C:\Users\Kristof\AppData\Local\Temp\pip-ephem-wheel-cache-p7vebfjn\wheels\30\8c\fc\66fc4c5a5e2a27aa97f29d147cee6bd5d1198260ae9d1e9102
Successfully built cx-Freeze
Installing collected packages: cx-Freeze
Successfully installed cx-Freeze-6.1
```

Thank you very much!

**Comment by marcelotduarte** [comment] 2019-12-06 11:59
Duplicate of #56

**Closed as completed by marcelotduarte** 2019-12-06 11:59 UTC

**Comment by marcelotduarte** [comment] 2020-01-05 04:48
cx_Freeze 6.1 has just been released.
