### ISSUE TITLE
why i can't install the latest 6.0 version of cx-freeze?

### ISSUE THREAD

**Issue by Javacppc** [marcelotduarte/cx_Freeze#542] opened 2019-12-18 08:41 UTC
I download cx_Freeze from https://github.com/anthony-tuininga/cx_Freeze/archive/6.0.tar.gz.
it may be the latest version.
but when l install it from the file
```
cd cx_Freeze-6.0
python3 setup.py install
```

And look the version:
`cxfreeze --version`
result is:
```
cxfreeze 6.0b1
Copyright (c) 2007-2017 Anthony Tuininga. All rights reserved.
Copyright (c) 2001-2006 Computronix Corporation. All rights reserved.
```

it always the 6.0b1 version.
not 6.0 version.
it is the same with `pip3 install cx-Freeze==6.0` and `pip3 install cx-Freeze`
so I face the problem which #513 has faced.that is when l copy the executable file to another centos7 machine:
```
Fatal Python error: initfsencoding: unable to load the file system codec
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/encodings/__init__.py", line 31, in <module>
zipimport.ZipImportError: can't decompress data; zlib not available
Aborted
```

Thank you!

**Comment by Javacppc** [comment] 2019-12-18 09:34
I download the master branch code of cx-freeze. the version is 6.1 and there is no problem above.but the link https://github.com/anthony-tuininga/cx_Freeze/archive/6.0.tar.gz is 6.0b1 version

**Comment by marcelotduarte** [comment] 2019-12-18 16:16
You can install the master branch with pip:
pip install --upgrade git+https://github.com/anthony-tuininga/cx_Freeze.git

Version 6.0 had this issue.
Duplicate of #503

**Closed as completed by marcelotduarte** 2019-12-18 16:16 UTC

**Comment by marcelotduarte** [comment] 2020-01-05 04:48
cx_Freeze 6.1 has just been released.
