### ISSUE TITLE
build app is ok, but bdist_msi is failed?

### ISSUE THREAD

**Issue by jekoie** [marcelotduarte/cx_Freeze#702] opened 2020-07-20 05:04 UTC
i use to `python setup.py build` is ok and run app well, but `python setup.py bdist_msi` is failed'?
<pre>
copying C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytz\zoneinfo\US\Pacific -> build\exe.win32-3.7\lib\pytz\zoneinfo\US\Pacific
copying C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytz\zoneinfo\US\Samoa -> build\exe.win32-3.7\lib\pytz\zoneinfo\US\Samoa
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    app.setup()
  File "setup.py", line 66, in setup
    executables=self.executables(),
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\dist.py", line 342, in setup
    distutils.core.setup(**attrs)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\windist.py", line 390, in run
    install = self.reinitialize_command('install', reinit_subcommands = 1)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\distutils\cmd.py", line 306, in reinitialize_command
    reinit_subcommands)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 938, in reinitialize_command
    command = self.get_command_obj(command_name)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py", line 858, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python37-32\lib\distutils\cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance

</pre>

**Comment by marcelotduarte** [comment] 2020-07-23 03:03
Duplicate of #693

**Comment by marcelotduarte** [comment] 2020-07-23 09:22
If you have a C compiler, you can test the development version:
`pip install -U git+https://github.com/marcelotduarte/cx_Freeze.git@develop`

**Closed as completed** 2020-08-24 00:44 UTC

**Comment by marcelotduarte** [comment] 2020-10-20 17:14
cx_Freeze 6.3 has just been released.
